### ISSUE TITLE
Registrations Should Have a Status

### ISSUE THREAD

**Issue by pingskills** [thewca/worldcubeassociation.org#1031]
The current design of the `registrations` table has `accepted_at`, `accepted_by`, `deleted_at` and `deleted_by` columns which allow for tracking the last changes to a registration. The problem is that the table can appear to be accepted and deleted, which actually means the registration is deleted.

It would be clearer to have a status field.

**Comment by jfly** [comment]
Switching to a status field would require us to track changed to that status somehow (presumably through a separate `registration_status_history` table or some such). One benefit of this would be that we'd be able to fully track the history of a registration (right now, when a registration is "ressurected", we lose its past history).

**Comment by larspetrus** [comment]
I think all you need can be done in code:

1. To get the state of a `Registration` object, have a status function on the object that computes it.
2. To query  for certain states, have predefined scopes/functions that does it right.

A new column with redundant information creates a new class of bugs: When the columns contradict each other.

**Comment by jfly** [comment]
Just to be clear about the current state of things, we have 3 states a Registration can be in:

- `pending` (aka: on the waiting list)
- `accepted`
- `deleted`

There are 4 database columns that drive these states:

- `accepted_at`
- `accepted_by`
- `deleted_at`
- `deleted_by`

Here's what can happen when I (Jeremy) register for a competition organized by Lars:

1. Jeremy registers. A Registration is created, `accepted_at`, `accepted_by`, `deleted_at`, and `deleted_by` are all NULL.
2. Lars approves Jeremy's registration. `accepted_at` is set to now, `accepted_by` is set to Lars. `deleted_at` and `deleted_by` are now NULL.
3. Lars realizes he should not have approved Jeremy's registration, so he deletes it. `deleted_at` and `deleted_by` are set to now and Lars, respectively.
4. Jeremy sees that he's not registered for the competition, and decides to register (maybe we shouldn't allow this, but currently we do). This clears all of `accepted_at`, `accepted_by`, `deleted_at`, and `deleted_by`. We have lost all the past history of this Registration =(

> A new column with redundant information creates a new class of bugs: When the columns contradict each other.

The idea behind this issue is to get rid of the 4 fields I mentioned above: `accepted_at`, `accepted_by`, `deleted_at`, and `deleted_by` in favor of a single `status` field that can be one of "pending", "accepted", "deleted". In addition, we'd have another table that tracks changes to this status field and *who* performed that change.

**Comment by larspetrus** [comment]
Aha. I missed the implied "instead". Sorry...

This makes sense.

So the new table could have these columns:

`registration_id`
`action`: `accepted`,`deleted`, `created`, etc
`action_at`: timestamp
`action_by`: user_id

Whether to remove the existing `created_at` and `updated_at` columns is debatable. I assume `accepted_at` would go, and ideally be migrated to the new schema.

**Comment by FatBoyXPC** [comment]
I'd be in favor of keeping created_at, and updated_at as well if the registration can get updated in a way other than updating the status.

**Comment by dunkOnIT** [comment]
It took us 8 years, but we did it
