### ISSUE TITLE
Multiple Iterations of Senior / regional delegate emails when organizer addition/removal notification is sent.

### ISSUE THREAD

**Issue by pranav-027** [thewca/worldcubeassociation.org#10320]
**Describe the bug**
Someone reported this on Discord: when an organizer is added or removed, or when the competitions are confirmed, the email contains duplicate iterations of the emails of senior/regional delegates.

**Screenshots**
Screenshot from Discord: 
![1](https://github.com/user-attachments/assets/b1030e12-117b-46fb-8100-74caecfa39ed)

Screenshots from my local testing:
![image](https://github.com/user-attachments/assets/c1a9ca06-9365-49c4-b75a-ba04ca29568e)

![image](https://github.com/user-attachments/assets/febcefdf-4274-4735-9210-49770586bbc7)

**Comment by gregorbg** [comment]
This error occurs because of a quirk in our Delegate role metadata join.

Some users are marked as Delegates multiple times, most notably if they have Senior/Regional responsibilities. In that case, there's one entry for them as a "normal" Delegate and once more in their extended role (Senior Delegate or Regional Delegate). This "ruins" the JOIN under the hood, making some rows appear multiple times.

I will point you to a "proper" fix directly on the relevant PR.
