### ISSUE TITLE
Allow senior delegates to promote/demote delegates

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1046]
Senior delegates are responsible for promoting/demoting delegates, and the Board has asked to give senior delegates the power to do this themselves. To keep an audit trail, we want to email board@ (and cc the person who took the action) whenever someone changes a delegate status. It is okay to give senior delegates the power to make someone a board member, however.

**Comment by jfly** [comment]
@cubewhiz, I've added to to an email thread about this titled "Allow seniors to edit delegate status?". Maybe let's continue the discussion over there.

**Comment by cubewhiz** [comment]
As per the email thread, please make the following changes, which have been approved by the Board:
(1) Change permissions so that Senior Delegates now have the ability to change Delegate status of users on the WCA website user pages.
(2) When a Senior Delegate changes the Delegate status of any Delegate (promotions, demotions, and new delegates), an automatic email shall be generated and sent to the WCA Board and WQAC.

Thank you.

**Comment by pedrosino** [comment]
@jfly can you help me out here?

I was trying to find the relevant code, and found this:
https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L405-L407

https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/views/users/edit.html.erb#L115-L126

https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/users_controller.rb#L128-L130

which gives the impression that any_kind_of_delegate can update the delegate status part.
What am I missing?

**Comment by jfly** [comment]
I believe this is guarded by the [`editable_fields_of_user`](https://github.com/thewca/worldcubeassociation.org/blob/f9c977d5bf367472ae9494f6d6258c4725ffd153/WcaOnRails/app/models/user.rb#L552) method.
