### ISSUE TITLE
Countries in competitors table is not localized

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#1140]
The admin part of registration is - the headers appear translated here.
But the public list of competitors is still in english.

**Comment by viroulep** [comment]
It is, but see #1111 :(

**Comment by viroulep** [comment]
Providing a screenshot of what I see locally, please re-open the issue if this is not what you're talking about:
![localized-registrations](https://cloud.githubusercontent.com/assets/1007485/22266963/45fb5314-e282-11e6-884d-ca25d37d3f73.png)

(and actually re-opening immediately because I notice on the screenshot that countries are still in English, and this is not cache-related)

**Comment by pedrosino** [comment]
This is what I see:
![table](https://cloud.githubusercontent.com/assets/1881933/22267260/4e60fcd8-e26a-11e6-9444-c995c6c53139.png)

**Comment by viroulep** [comment]
Ok, the table headers it's because of #1111, and the country names is a separate issue.
Fixing it now too.

**Comment by jonatanklosko** [comment]
That's exactly why I created #1111 =)
