### ISSUE TITLE
Do not allow delegates to assign WCA IDs that are missing birthdays

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1173]
Garret Webster ran into this for an upcoming competition. David Woner assigned a WCA ID to a registrant, and the person for that WCA ID did not have a birthdate in our database, so we ended up with a registrant without a birthdate, and we have validations that says registrants must have birthdates, so it was impossible to approve the registration.

I'm going to add a validation to our users model that says users cannot be assigned WCA IDs without birthdates. I'll also check if we have any existing users with birthdayless WCA IDs.

**Comment by SAuroux** [comment]
Hi Jeremy,

was David Woner contacted about this?

Am 28.01.2017 7:05 AM schrieb "Jeremy Fleischman" <notifications@github.com
>:

Closed #1173
<https://github.com/thewca/worldcubeassociation.org/issues/1173> via #1174
<https://github.com/thewca/worldcubeassociation.org/pull/1174>.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/thewca/worldcubeassociation.org/issues/1173#event-940191483>,
or mute the thread

**Comment by jfly** [comment]
Nope, I never talked to David about this directly, just Garret.
