### ISSUE TITLE
Add explicit fields to competitions for competitors limits

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/worldcubeassociation.org#1325]
The WCA Board has found that the competitors limits are the most relevant details about a competition that we still don't have in specific fields in our structure.  We would love to have:
- competitors limit (integer - public - optional)
- reasons for the limit (text - private - mandatory if limited)

Additionally you should consider to have a boolean / flag asking if the competition is limited and showing / hiding the two fields above, but this is up to the creativity of the programmer.

**Comment by larspetrus** [comment]
What kind of things would be the reasons, and why does the board and others need to know?

If there is a set of 5-10 standard reasons, could this maybe be a dropdown?

**Comment by jfly** [comment]
It is also worth noting that a simple "integer competitor limit" doesn't encompass all of the things that competition organizers are allowed to do by the regulations. See [Z2](https://www.worldcubeassociation.org/regulations/#Z2) and [Z4](https://www.worldcubeassociation.org/regulations/#Z4).

**Comment by larspetrus** [comment]
Is the competitor limit only informational, or do you expect the app to enforce it somehow?

**Comment by Luis-J-Ianez** [comment]
@jfly, you're right, but for the moment an integer for just the case of "competition limited to X competitors" is all what we'd like to have.  The rest of (unusual) cases can still be handled with the remarks box and an internal discussion by email.

@larspetrus, the competitors limit (when set, that is, > 0) must be public.  The reasons must be only visible under the "admin view".  And please, do not add a drop down for reasons --let the board enjoy the delegates' imagination. ;)

Oh, and according to our guidelines, the limit _should_ be 12 or above.  So, I guess any integer >= 0 should be acceptable for this field.  I see no reasons to publicly state the limit when this field is zero.  For the rest of cases, a sentence stating "Competition limit    X competitors" (or similar) under "fee" in the "General info" tab could work fine.

**Comment by Luis-J-Ianez** [comment]
About enforcing the limit (in the registry, I assume), I'm not sure.  I guess we shouldn't --there's nothing wrong in accepting beyond the limit as long as the waiting list is respected.  @pedrosino?

**Comment by jfly** [comment]
Also, please see #328.

**Comment by SAuroux** [comment]
I fully support these idea. This will hopefully help the Board to evaluate
competitor limits more carefully in the future.

Regarding the implementation, I would actually propose the following:

   - competitor limit? (boolean - public - mandatory)
   - desired limit (integer - public - mandatory iff limited=True)
   - reasons for the limit (text - private - mandatory iff limited=True)


2017-02-14 19:09 GMT+01:00 Jeremy Fleischman <notifications@github.com>:

**Comment by pedrosino** [comment]
I'm not sure what @larspetrus meant by enforcing, but if he means "enforcing that the organizer/delegate must set some kind of limit", the answer is no. I like Sébastien's proposal of a boolean indicating limit or not, and the other 2 fields only visible and mandatory if the boolean is true.

About applying the limit to registrations, I'm also not sure it is a good idea. We could try to move to a system where registrations over the limit are moved to an actual "waiting list" and the registrant is informed properly, and where the organizer/delegate would only be allowed to accept new registrations over the limit if one registration is somehow deleted.
That could work, but would require more effort to implement, so I think we should stick to the original, simple idea for now.

About #328, I think our registration flow has changed quite a bit since then, so some of the ideas there no longer apply and/or need re-thinking.

**Comment by larspetrus** [comment]
On Wed, Feb 15, 2017 at 5:26 AM, Pedro Santos <notifications@github.com>
wrote:

> I'm not sure what @larspetrus <https://github.com/larspetrus> meant by
> enforcing
>

I meant that if the competition limit is set to 200, the app should somehow
limit the number of competitors to that number.


-- 
Procrastinators - the Leaders of Tomorrow
