### ISSUE TITLE
Entries on the Competition Page Should Span 1 Line

### ISSUE THREAD

**Issue by gyroninja** [thewca/worldcubeassociation.org#1332]
For example take a look at Silent Spring 2017 from https://www.worldcubeassociation.org/competitions?region=USA

https://i.gyazo.com/7057766ffedf916da01b1a25e5bd78d7.png

Notice that the location is so long that it flows over into a new line.

We should either:
* resize the table like we currently do when someone has a resolution that is too small to fit it
* limit the length of the location string to a fixed size (would this be effected by user's resolution?)
* a different creative solution

**Comment by jfly** [comment]
Including @gyroninja's image inline to make it easier for people to read:

![image](https://cloud.githubusercontent.com/assets/277474/23036326/3eb88222-f437-11e6-9104-ebd2bf816aca.png)

Honestly, the problem here is that the delegate filled out the fields wrong. The "Venue" field is not supposed to contain an address, that's what the "Venue address" field is for. See the admin page here:

![image](https://cloud.githubusercontent.com/assets/277474/23036323/3c869afc-f437-11e6-9d37-ecc9c4c874ba.png)

Maybe we could do some work here to detect/prevent these situations, but I'm loathe to spend the time picking a maximum number of characters for this field. We've got much more impactful work to be doing, so I'm going to close this issue.

I will ping Chris Tran and the Board (and CC you) about cleaning this specific competition up.

**Comment by larspetrus** [comment]
There are ways to force this in CSS. I've never used it, but `white-space: nowrap` would probably work.

**Comment by jfly** [comment]
We've actually crafted this table very carefully to look good on mobile as well, and IIRC, `white-space: nowrap` could break our precious effort. If someone is motivated to look into this, please remember to try things out on mobile as well.
