### ISSUE TITLE
Add a WRC section

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#1593]
It's difficult to find the relevant issue in the WRC repository because people assume it's here. Therefore, I am adding this here so things won't get lost.

The WRC would like to have a section on the website sooner or later.
I created a draft [here](https://github.com/thewca/wca-regulations/issues/419#issuecomment-294306580).
Noobish implementation is [here](https://github.com/Laura-O/worldcubeassociation.org/tree/WRC-section).

The news section could (or should) be implemented together with other plans (especially the plans the WCT has or might come up with).

**Comment by jfly** [comment]
@Laura-O, I've assigned this to you, because you've already taken the initiative and started coding. As you think of more stuff to do, it might make sense to break this issue up into lots of tiny issues. Whatever works for you! You can decide how much coding you want to do vs recruiting folks from the WST to help out.
