### ISSUE TITLE
Newly registered competitor has access to a page they shouldn't see

### ISSUE THREAD

**Issue by SqAtx** [thewca/worldcubeassociation.org#1624]
I registered to a competition today and after paying the fee there was a button named something like "Update registration". I clicked on it and it opened this page:
![wca](https://cloud.githubusercontent.com/assets/4351932/25984075/5c34d4a6-369d-11e7-99b5-36e3049c3ec9.PNG)
I'm pretty sure I was not supposed to see that.
I didn't reproduce the problem because that requires me to actually register to a competition.

The page now returns an error message.
![wca2](https://cloud.githubusercontent.com/assets/4351932/25984120/a59e9a82-369d-11e7-8188-82c23e0b88d1.png)

**Comment by jfly** [comment]
Here's the problematic code: https://github.com/thewca/worldcubeassociation.org/blob/54b9f1a42b68b3600338c215c391e17935db522a/WcaOnRails/app/controllers/registrations_controller.rb#L185-L186. You can see we unconditionally render `edit` here, even if the user did not come from the admin view. This isn't a security flaw, but it's certainly confusing.

The reason the page now returns a error message is because you're doing a HTTP GET to the same url that you previously had done a HTTP POST to.
