### ISSUE TITLE
New bundler fails Travis

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#1656]
See  #1655.

**Comment by jfly** [comment]
I just talked to @jonatanklosko about this. Travis upgraded bundler from 1.14 to 1.15 and it's causing our pre-commit gem to die. There are 4 things we need to do:

1. downgrade bundler in travis so it's running version 1.15.
2. upgrade our pre-commit gem so we have the latest pluginator
3. create an issue on pluginator about the type conversion problem
4. create an issue on pre-commit about not working on bundler 1.15 because of #3

**Comment by jonatanklosko** [comment]
@jfly I downgraded the bundler version in #1660, but restarting Travis didn't help as you expected so I made a new PR with translations update and it went well (also commented on other PRs affected by that) + deployed the forum thing as it was failing too. Then I updated pre-commit (and thus pluginator) to the latest version locally and created issues with the appropriate error, see rvm/pluginator/issues/10 and jish/pre-commit/issues/258.

**Comment by jonatanklosko** [comment]
This has been fixed in #1660, though not perfect, I'm closing in favour of #1662.
