### ISSUE TITLE
Bug in persons_finish_unfinished caused by apostrophes

### ISSUE THREAD

**Issue by Luis-J-Ianez** [thewca/worldcubeassociation.org#1726]
I have a vague recollection that this was already fixed, but I've found today that the second step of this script (the one adding newcomers to persons) doesn't work like expected when the person's name includes an apostrophe. The second part of this script performs an INSERT into persons and then an UPDATE to write gender and country. The UPDATE fails because the name is not escaped, I guess. (I should have copied the SQL queries, but I didn't, sorry. :/ )

**Comment by jfly** [comment]
@Luis-J-Ianez, could you search through your inbox for an email thread titled "Problem with names that include an apostrophe" (created by @pedrosino)? In that thread, we discussed this very problem, and I believe we fixed it (we intentionally did not bother to fix the highlighting code, so that could be confusing).

Are you able to reproduce this bug on staging? If so, please repoen this issue and comment with instructions for how to recreate it, and we'll look into it.
