### ISSUE TITLE
The first result on google for "wca scrambler" is our website, but it's not TNoodle

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1851]
I just had an interesting conversation with a cuber. See

![image](https://user-images.githubusercontent.com/277474/29546605-491fe858-86aa-11e7-9b2b-62f3a4df82ea.png)

It turns out that [this outdated scrambler](https://www.worldcubeassociation.org/regulations/history/files/scrambles/scramble_cube.htm) is the first result on google for [wca scrambler](https://www.google.com/search?q=wca+scrambler) =(

![image](https://user-images.githubusercontent.com/277474/29546626-654da006-86aa-11e7-8071-ed8706a5ba1b.png)

@Laura-O, @lgarron any ideas for fixing this? Maybe change this page to have a big header that says something about this being outdated? Maybe change the page to just redirect to https://www.worldcubeassociation.org/regulations/scrambles/

**Comment by lgarron** [comment]
I don't see a *huge* problem with this, because delegates should know where to find the right scramble program.

I think it would be fine to change the title to say "legacy" and add a warning at the top with a link to the current scramble program.

I think we definitely should not redirect without notice – I would rather put the historical stuff into a .zip linked from [the history page](https://www.worldcubeassociation.org/regulations/history/) and redirect there.

(Also note that "WCA [scrambler](https://www.worldcubeassociation.org/regulations/#1f)" is technically a competition official.)

**Comment by Laura-O** [comment]
The old regulations (like [2004](https://www.worldcubeassociation.org/regulations/history/files/regulations2004.html)) link to these pages and just redirecting to the TNoodle page might give the impression that we already used TNoodle back then.

So I think adding a huge header with a link would be the best solution.

@lgarron There already is a [zip-file](https://www.worldcubeassociation.org/regulations/history/files/scrambles.zip).

**Comment by jfly** [comment]
Updating the title sounds good to me! @Laura-O, do you mind taking this on? If you don't have time, let me know and we'll find someone else to do it.

**Comment by Laura-O** [comment]
I won't have time for that in the next 2-3 weeks. So if this can wait until early-/mid-September I can do that. But I won't complain if you find someone else in the meantime. :-)

**Comment by jfly** [comment]
No worries, @Laura-O. Hey @coder13, do you have some time to work on this?

**Comment by coder13** [comment]
Will do.

**Comment by timhabermaas** [comment]
@Laura-O This can be closed thanks to #2000, right?

**Comment by Laura-O** [comment]
Yep. :-)
