### ISSUE TITLE
Set up linting and style checking for javascript

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#1924]
It's important that this work on both js and jsx files. It would be particularly awesome if it also works on javascript inside of html and javascript inside of erb, but it's okay if that's not easy to do.

(See https://github.com/thewca/worldcubeassociation.org/pull/1856#discussion_r137937415 for some discussion about indentation of promises)

**Comment by jfly** [comment]
I know that pre-commit does some linting of javascript for us, but I think it's only configured to run on js files, and it might not be aware of es2016+ stuff that we're doing now.

**Comment by UnsolvedCypher** [comment]
I think it might make sense to switch to something like ESlint which does a very good job of enforcing both code style and catching anti-patterns. Maybe we could add the ESlint and a config and then add it as a pre-commit once all of the initial errors have been worked through?

**Comment by viroulep** [comment]
Since #4381 we actually use the `overcommit` gem which runs jshint on our codebase before commits!
However, while I've seen some errors being reported on the js files I wrote, I haven't seen some on jsx.
Overcommit seems to [have something ready](https://www.rubydoc.info/github/brigade/overcommit/Overcommit/Hook/PreCommit/EsLint) for ESlint, I'd definitely be interested to see what it has to say about our code.
Is that something you would like to try integrating?

**Comment by UnsolvedCypher** [comment]
I'd be interested in trying to integrate this if the WST thinks it's a good direction to go in.

I ran ESlint on the JavaScript code to see what kind of errors it would get. For the most part:

- functions used before they are defined
- strings not being consistent in quotes used (single vs double)
- incorrect indentation
- incorrect spacing (such as missing between `if` and `(`
- use of `var` instead of `let` or `let` instead of `const`
- line length > 100

Over 75% of the issues raised can be automatically fixed by ESlint. I'm sure some of the other ones are false positives that would need to be fixed by further configuration.

**Comment by viroulep** [comment]
Yes, if we can run this over the whole code base (js + jsx) that would be very nice to ensure we have a consistent coding style over the whole code base.
Would you be able to submit a draft PR with the appropriate settings for overcommit (if you did look into it, or just how you ran it if you ran/configure it manually), as well as the automatic fixes?
This way we could have a place to discuss if we are happy with eslint reports and also how we can handle the other errors raised!

Thanks for looking into this!
