### ISSUE TITLE
Export competitors for competitions in tsv export

### ISSUE THREAD

**Issue by loovjo** [thewca/worldcubeassociation.org#1953]
Right now the competitors that competed in a competition is not stored in the exported tsv data. This would be useful to make it easier to see who competed where, who won different competitions and also who will compete in upcoming competitions.

**Comment by jfly** [comment]
Can't you figure this out by looking at the `Results` table, which shows you every result for every competitor? (I'm closing this issue, feel free to reopen if I'm missing something.)

**Comment by loovjo** [comment]
Yes, but you can't see competitors for upcoming competitions unless I'm missing something.

**Comment by jfly** [comment]
I see, yes, that is something we currently do not expose publicly. I don't think it would be very useful though, because only some competitions use the WCA website for registration.

**Comment by loovjo** [comment]
I see. Is there any chance of being able to get the information in the future?

**Comment by loovjo** [comment]
Well, at least right now it seems like it's quite rare for competitions _not_ to use the WCA website to handle registrations. I don't see any reason not to export this information when you can easily go to the page and look at the competitors page yourself, the information is already publicly available.

I think seeing the competitors of upcoming competitions can be useful, I'm currently developing an application where you're supposed to be able to select a competition and see what chances you have of making different rounds and/or winning in different events. This is pretty much impossible when you can't tell who you're competing against. So I do think this can be really useful information and I don't see any reason not to export it.

(Sorry if this is a little bit ranty, I just really want this to be exported)

**Comment by Baiqiang** [comment]
@loovjo In fact, 25% competitions don't use WCA registration system. That's not quite rate IMO. For example, all Chinese and Taiwanese competitions.

**Comment by Laura-O** [comment]
> I don't see any reason not to export this information when you can easily go to the page and look at the competitors page yourself, the information is already publicly available.

I disagree here. I think there is a clear difference between being able to check all registration lists manually and being able to retrieve traveling plans for each competitor.

**Comment by jfly** [comment]
@Laura-O, I don't see the distinction you're making. What do you mean by travelling plans? All we're talking about is showing what competitions people might go to, not where they plan to sleep or how they plan to travel there. As @loovjo said, this information is already public, and it's pretty trivial for someone to write a script to scrape this information if they want to.

@loovjo, the WST is working on a new data format called [WCIF](https://docs.google.com/document/d/1jiGjmBoG_-5uZOF3RicMKZmZEI7rcPaQ6ax5z785vVs/), which should include a psych sheet (if the competition is using WCA registration). However, the WCIF api is currently not publicly accessible, because it includes birthdays (which are considered private information). No one is currently working on adding a public WCIF api, but if you are interested in working on that, then you'd be able to get the information you want from the website.

**Comment by Laura-O** [comment]
> @Laura-O, I don't see the distinction you're making. What do you mean by travelling plans? All we're talking about is showing what competitions people might go to, not where they plan to sleep or how they plan to travel there. As @loovjo said, this information is already public, and it's pretty trivial for someone to write a script to scrape this information if they want to.

"Pretty trivial" is probably not true for the majority of people who could be interested in this information. It's rather pretty trivial to download the database and open the table in Excel, which would be possible if this information is available in the export.
This would mean that anyone just needs three clicks to see to which competitions I am going. Checking all competition pages for European competitions in the next months manually takes much more time.
