### ISSUE TITLE
Make competition managers able to set a championship type

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#1982]
For now, only admins can set a championship type. We should certainly allow delegates to set this before the competition goes confirmed.

**Comment by jfly** [comment]
If we allow delegates to set a competition as a championships, we should only allow them to do that when the competition is unconfirmed. Furthermore, I think we should update the confirmation email so it's really obvious that this competition is proposed as a championship, so the board doesn't miss it.

Alternatively, the board might just want delegates to explicitly ask for a competition to be marked as a championship, rather than letting delegates mark it. If that's the case, then the current behavior is fine, although our delegates should probably be reminded to ask about this for all future competitions. Could you email the board and ask them how they'd like things to behave? 

Whatever we decide here, we should definitely update the delegate crash course with directions about how delegates should handle this.

**Comment by jonatanklosko** [comment]
Right, so The Board has decided that they prefer the first solution.

> We'd like to remark that this ability can be granted to delegates only when the competition unconfirmed, and that the notification email must state very clearly that the request if for a championship.
