### ISSUE TITLE
Prevent cron from running on old server instances

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#2020]
When we spin up a new server and switch to it, leaving the old one running, we should make sure that cron is not running on the old instance.

This comes as a conclusion from an issue we run into. The weirdness was that scheduled jobs were enqueued every hour, but for each type there were 3 jobs (e.g. 3 linkings computations, 3 delegate report nag email jobs). As the database is shared among server instances, each instance (including 2 old ones) run its cron job every hour, and it resulted in more jobs of the same type.

**Comment by larspetrus** [comment]
Interesting problem...

I kinda hate cron jobs  because they're entirely separate from the Rails app so there aren't really any good tools to coordinate between the worlds and avoiding a mess will always depend on manual awareness.

You could imagine a place in the DB where it's noted what the "official" prod server is, and each cron job would have to check it before executing. But that probably creates more problems than it solves. Personally I'd aim for a cron free system.
