### ISSUE TITLE
Form for submitting competition results

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2113]
Tangentially related to #2073, but probably more important.

- [x] ~~check that the `/events` page has been filled in (so the WRT can enforce time limits)~~ see https://github.com/thewca/worldcubeassociation.org/issues/2984
- [x] update the submit results nag email to link to this new form (#2979)
- [x] add a required field linking to the competition schedule (https://github.com/thewca/worldcubeassociation.org/pull/2983 and https://github.com/jfly/worldcubeassociation.org/pull/2)

**Comment by jfly** [comment]
Copy pasting information about submitting results from the delegates crash course:

Submitting competition results
Once obtained from the WA, the JSON file is to be submitted to the Results Team: results@worldcubeassociation.org. Please make sure, to include all helpful information for the results team in the text body of this mail:

New: To allow the Results Team to verify time limits and cutoffs, you must provide a link to the competition's schedule. If this schedule does not contain the final time limits and cutoffs (as applied at the competition), please list them separately.
Are name changes requested? If so, which version of the name is included in the submitted JSON file?
Are dates of birth missing or are you unsure if a WCA-ID is missing? (see sections above)
Have events been added or removed compared to the original competition anouncement?
Are there records that should be declined due to regulation 9i2)? Please help us by providing a link to the competition schedule in such a case.
What was the main event at the competition? (This relates to the results announcement. In particular, for competitions not hosting 3x3x3, it should always be mentioned if another event should be considered as the competition's main event or not. If no note about this is added, the Results team will always consider 3x3x3 as main event for competitions with 3x3x3 and 'no main event' for competitions without 3x3x3.)
Anything else that is of importance for the results team? Please don't hesitate to include it, the more detailed, the better.

**Comment by pedrosino** [comment]
Just to be a little picky, this comma is not necessary, I think:
> Please make sure**,** to include all helpful information

**Comment by jfly** [comment]
You're totally right. I've updated the [crash course](https://www.worldcubeassociation.org/delegate/crash-course) to remove that extra comma.

**Comment by SqAtx** [comment]
So this ticket has a lot of small changes. I think it would help to write them down.

We talked about splitting it a bit, start with something simple and work towards the desired workflow.
### Step 1: Add a page for submitting results
* Add a new "Submit results" navigation item in the delegate view of a competition, probably just above "Delegate report"
* It opens a simple view with a file upload, a text input, and a Submit button
* Clicking the button sends an email:
  * To the results team
  * CC to the delegates of the competition
  * With "Results for \<competition-name\>" as subject and the content of the text input as body
  * With the uploaded file attached

It's not a very efficient workflow but that's a good first step! I'd have a code review at that point.

### Step 2: Implement the constraint and encourage delegates to use the form
* check that the /events page has been filled in (ie check that all events have at least one round). If not, the Submit button is greyed out and there is a note similar to the "Your report is not posted yet! Click here to work on it." to explain why
* update the submit results nag email to link to this new form

At this point, we can theoretically use this workflow because it adds value compared to just sending an email.

### Step 3: Polishing for better user experience
* The Submit button is unavailable unless a file has been uploaded and something has been written in the email body
* ...

At this point, I would consider this ticket done.

Then we can create new ones for improvements.
### New ticket 1
Check the JSON file against the information filled in the /events page.
* Make sure it contains the correct events and rounds.
* Make sure the time limits and cutoffs have been respected

### New ticket 2
Have the form upload the JSON file to the website instead of emailing it to the results team. Probably have some kind of validation from the results team.
