### ISSUE TITLE
Add a birthdate column to Persons

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#2189]
Right now we have separate colums for year, month and day, which is quite annoying to use when you need birthdate information and/or operations.

Is there a specific reason for this?
We already have start_date and end_date for Competitions (the old columns are still there, though), so it would make sense to have this for Persons as well.

**Comment by jfly** [comment]
We were able to make this change to the Competitions table because only Rails code updates the Competitions table, so we can use ActiveRecord hooks to keep all the columns in sync. That's not possible with the Persons table because we have PHP scripts that write to the Persons table. So, before we can make this change, we need to first get rid of all the PHP code that writes to the Persons table.

**Comment by pedrosino** [comment]
Ah, that sucks :(

**Comment by danieljames-dj** [comment]
This is being addressed by @gregorbg here: https://github.com/thewca/worldcubeassociation.org/pull/7983.

**Comment by gregorbg** [comment]
Closed via https://github.com/thewca/worldcubeassociation.org/pull/7983
