### ISSUE TITLE
Default to 75% when people are selecting an advancement condition

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2297]
Suggested by @SAuroux.

**Comment by SAuroux** [comment]
a bit more specific: put 75 as default value instead of 0 when selecting an advancement condition AND when selecting "Percent" from the dropdown in the next step.

reasoning: 
- 75% is used by the vast majority of cases when a percentage is used as advancement condition
- changing the value from 0 to 75 every time requires many unncecessary clicks/key strokes

**Comment by moralsh** [comment]
Got this solved on my local git, I'll push it to my fork as soon as I change the reference of my local git.

**Comment by moralsh** [comment]
Created pull request #2333
