### ISSUE TITLE
Add average of 5 as an allowed (and the preferred!) format for 333ft

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#2369]
See https://github.com/thewca/wca-workbook-assistant/pull/117 and https://www.worldcubeassociation.org/regulations/#9b1.

@viroulep, as our WRC+WST member, could you take this on?

**Comment by viroulep** [comment]
I can take a look, but since the changes will impact results uploading and I know almost nothing about it, I'd love to have an eye from @SAuroux.

Sébastien, do you expect to have to upload any more results with feet Mo3?

I guess we just need to update the [seeds](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/db/seeds/preferred_formats.seeds.rb#L13) and setup a migration.

Then I'll setup the PR on staging for testing.

**Comment by SAuroux** [comment]
All with feet results of 2017 have already been posted, so I don't expect any needed support for Mo3 in the future.

Unfortunately, I won't have time to test this new WA version before next week (which will be too late), so it would be good if someone else could do this.
