### ISSUE TITLE
Latest regulation release missing in history

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#2380]
The [regulation history](https://www.worldcubeassociation.org/regulations/history/) wasn't updated with the new regulation release yet.
It would be great if someone could update the history and add the link to the page.

**Comment by jfly** [comment]
Historically, that page has always been updated by the WRC. Could you or maybe @viroulep send in a PR with the changes? Thanks!

**Comment by Laura-O** [comment]
Yes, I can probably do that. I just need a confirmation that what I would do is correct. 🙂 

What I would do:
1. Add a new folder with the new regulation files in `regulations/build/regulations/history/official/` in the `regulations-data` branch and create a PR
2. Create another PR to update the history page in `master`

**Comment by viroulep** [comment]
The last time I did it, I had [this PR](https://github.com/thewca/worldcubeassociation.org/commit/46163cfc3ecf69ed9cefa2dde7eb672ae556df13) for `regulations-data`, and [this one](https://github.com/thewca/worldcubeassociation.org/pull/747) for master.

What you suggest sounds good, in the new folder I would put the files generated by `wrc --target=html`, including a disclaimer (like [here](https://github.com/thewca/worldcubeassociation.org/commit/46163cfc3ecf69ed9cefa2dde7eb672ae556df13#diff-831b7218f7e202f582527a37cc79672dR3)), and "history" instead of "official" in the same line.
