### ISSUE TITLE
Some competition page is down in zh-CN

### ISSUE THREAD

**Issue by Baiqiang** [thewca/worldcubeassociation.org#2613]
1. Switch to zh-CN
2. Open some competition page. e.g. https://www.worldcubeassociation.org/competitions/SingaporeChampionship2018
3. It shows "We're sorry, but something went wrong.".

Firstly I think it may be caused by missing some translation. But later I found only in zh-CN it's down.

**Comment by viroulep** [comment]
Went quickly through the log and found this:

> F, [2018-02-26T09:16:56.755209 #20738] FATAL -- : [c65d0054-fa96-4db8-85f4-c8e81e827903] ActionView::Template::Error (translation data {:zero=>"主办方", :other=>"主办方"} can not be used with :count => 1. key 'one' is missing.):
F, [2018-02-26T09:16:56.755349 #20738] FATAL -- : [c65d0054-fa96-4db8-85f4-c8e81e827903]     22:       <dd><%= link_to "#{competition.name} website", competition.website, target: "_blank" %></dd>
[c65d0054-fa96-4db8-85f4-c8e81e827903]     23: 
[c65d0054-fa96-4db8-85f4-c8e81e827903]     24:       <% if competition.organizers.length > 0 %>
[c65d0054-fa96-4db8-85f4-c8e81e827903]     25:         <dt><%= t('.organizer_plural', count: competition.organizers.length) %></dt>
[c65d0054-fa96-4db8-85f4-c8e81e827903]     26:         <dd>
[c65d0054-fa96-4db8-85f4-c8e81e827903]     27:           <%= users_to_sentence competition.organizers, include_email: false %>
[c65d0054-fa96-4db8-85f4-c8e81e827903]     28:         </dd>

It's so weird because all zh-CN pluralizations have only zero and other defined and it used to work just fine.
Maybe rails has changed something in his pluralization rule for this locale?!

**Comment by Baiqiang** [comment]
@viroulep Thanks for digging this. Any idea to solve this quickly?

**Comment by viroulep** [comment]
Oh see svenfuchs/rails-i18n#767.
They released a fix a few hours ago, I'll try to see if we can bump our rails-i18n to this version.
