### ISSUE TITLE
Rename "waiting list" to "pending approval"

### ISSUE THREAD

**Issue by shelchang** [thewca/worldcubeassociation.org#2625]
"Pending approval" is a much more accurate description for what is currently called a "waiting list". I've fielded questions from so many people thinking registration was full because they were on a "waiting list".

**Comment by ToastyKen** [comment]
Ditto. I just want to back this up with saying that while these people are technically "waiting" for approval, the term "waiting list" has a strong connotation that registration is full, and that people are waiting for spots to open up.

It's my understanding the reason is that the same functionality is used when registration actually hits the limit, at which point it does become a waiting list.  I think it's important to make that distinction.

Proposal:

1) When registration is not yet full, the confirmation email tells competitors that their registration is "pending approval".
2) At the time that registration fills up, everyone who is already pending approval get a NEW notification telling them that registration has filled, and that they are now on the "waiting list".
3) After registration is already full, new registrations get confirmation emails that tell them they are on a "waiting list".

**Comment by cubewhiz** [comment]
This is already covered in #2413.

**Comment by jfly** [comment]
@ToastyKen, you're correct that this list has both meanings. We can't programmatically do what you ask for because we currently don't programatically know if registration is full or not. I'm going to close this as it is covered by #2413 (as @cubewhiz already pointed out).

**Comment by timreyn** [comment]
@jfly, you said:

> we currently don't programatically know if registration is full or not

why is this?  We have a competitor limit for each competition, and we have the list of accepted competitors, why can't we just compare the two?

**Comment by pedrosino** [comment]
I guess he doesn't mean we "can't" but rather that we "don't do it yet".

**Comment by timreyn** [comment]
Ah, got it :)

**Comment by Goosly** [comment]
Actually, for example in the Netherlands they currently use a system where they accept X competitors **per day**.

**Comment by Goosly** [comment]
Actually, in the Netherlands they currently accept X competitors **per day**, so if the limit is 100 there might be 110 registrations accepted because 10 people only go on Saturday and another 10 only on Sunday.

So this idea wouldn't work for them (or they would have to stop using that system).

**Comment by cubewhiz** [comment]
Per day limits are not explicitly allowed by the Regulations so cases in which they have been used have required Board approval on an individual basis. There are other ways around this, so I don't think per day limits should be a valid reason to block the software implementation. Indeed, the easier solution is to disallow per day limits.
