### ISSUE TITLE
Trinidad and Tobago is considered South America in the database but it is actually North America

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#2647]
>

**Comment by jfly** [comment]
This data is actually maintained by @thewca/wrc-team over in https://github.com/thewca/wca-regulations/blob/draft/wca-states.md. @viroulep, do you think you could take care of this?

Also cc-ing @SAuroux to comment on if there will be any trickiness with our results database. I think the only concern would be continental records, which doesn't look like an issue because [Philip Habib]() is [our only competitor representing Trinidad & Tobago](https://www.worldcubeassociation.org/persons?search=2012HABI02&page=1&region=Trinidad+and+Tobago)..

@Mollerz, for posterity, it would be nice to have some explanation about why we consider Trinidad and Tobago to be in North America. After some very light googling, it maybe sounds like geographically it's more South America, but politically and economically it's more North America?

**Comment by Mollerz** [comment]
Yeah it lies on the South American shelf but the only countries that are part of South America are all on the mainland and all Caribbean islands are considered North America.

See also: https://gyazo.com/0d919356499a31c35e067484ae510dcd

**Comment by Mollerz** [comment]
@viroulep

**Comment by viroulep** [comment]
Thanks for the ping James!

**Comment by viroulep** [comment]
Fixed in #2907.
