### ISSUE TITLE
Simplify Preregs schema

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#275]
We really only need `user_id`, `competition_id`, `status`, and a list of registered events... however, we're going to have to support the old schema for a while, until all upcoming competitions only have Registrations with a user_id.

Upcoming competitions using WCA registration:

```SQL
SELECT * FROM (
  SELECT id, CONCAT(`year`,'-',LPAD(`month`,2,'00'),'-',LPAD(`day`,2,'00')) as start_date
    FROM Competitions
    WHERE use_wca_registration=1
) as c
WHERE start_date > CURDATE()
ORDER BY start_date DESC
```

Upcoming competitions that have some Registrations without a user_id (meaning their registration started with the old PHP system):

```SQL
SELECT DISTINCT(competitionId), year, month, day
  FROM registrations JOIN Competitions ON registrations.competitionId=Competitions.id
  WHERE registrations.user_id IS NULL AND CONCAT(`year`,'-',LPAD(`month`,2,'00'),'-',LPAD(`day`,2,'00')) > CURDATE()
  ORDER BY Competitions.year DESC, Competitions.month DESC, Competitions.day DESC
```

```
competitionId	year	month	day
OpenCubeProject2016	2016	4	16
GermanOpen2016	2016	4	9
TulipOpen2016	2016	3	20
MilanSlamOpen2016	2016	3	13
Murcia2016	2016	3	5
CubeateWeekend2016	2016	2	27
SingaporeOpen2016	2016	2	20
SalgadoOpen2016	2016	2	14
MolinaOpen2016	2016	2	13
PhalsbourgWinterOpen2016	2016	2	13
UchiMontevideo2016	2016	2	12
IranOpen2016	2016	2	11
UiOOpen2016	2016	2	7
UralWinter2016	2016	2	6
ZaragozaOpen2016	2016	2	6
SCMUOpen2016	2016	2	6
SSSARubik2016	2016	1	30
Generalen2016	2016	1	30
ManchesterOpen2016	2016	1	30
CamarmaOpen2016	2016	1	30
GoodNutritionCubeDay2016	2016	1	24
MoldavianNationalsWinter2016	2016	1	23
OxenteOpen2016	2016	1	23
AdelaideSummer2016	2016	1	23
ShaastraCubeOpen2016	2016	1	23
HaNoiCubeDay2016	2016	1	17
BandungOpen2016	2016	1	16
NepalOpen2016	2016	1	16
ChottuSkips2016	2016	1	16
URARubikOpen2016	2016	1	16
HorizonCubeOpen2016	2016	1	16
```

**Comment by jfly** [comment]
We should also probably pull the list of events a competitor is registered for out into separate join table.

**Comment by pedrosino** [comment]
select distinct Preregs.name, users.name, users.id from Preregs, users, Persons, Competitions
where Persons.id = users.wca_id 
and Preregs.personId = Persons.id 
and user_id is null 
and users.encrypted_password <> '' 
and users.email <> concat(Persons.id, '@worldcubeassociation.org')
and Competitions.id = Preregs.competitionId
and Competitions.year = '2016'
ORDER BY users.id

gave me 311 people which are registered with php and have an account and a WCA id (another 1500+ have a dummy account)

So I just ran

update Preregs,users,Persons,Competitions set Preregs.user_id = users.id
where Persons.id = users.wca_id 
and Preregs.personId = Persons.id 
and Preregs.user_id is null 
and users.encrypted_password <> '' 
and users.email <> concat(Persons.id, '@worldcubeassociation.org')
and Competitions.id = Preregs.competitionId
and Competitions.year = '2016

but it crashed, because some people have duplicated registrations...

**Comment by jfly** [comment]
Wow, time flies. As OpenCubeProject2016 occurred last weekend, we can finally do this!

**Comment by jfly** [comment]
I'm going to leave this until the end of May, so we can tackle it along with #403.

**Comment by jfly** [comment]
My plan at the end of the month is to create a new table called `old_Preregs`. We'll move all registrations from past competitions to there, and then remove unused columns from the Preregs table, and rename Preregs -> registrations. After we do that, we can then make the assumption that all Registrations have a corresponding User, and we can move these silly [wrapper methods](https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/app/models/registration.rb#L72-L79) from the Registration class to the User class.

**Comment by jfly** [comment]
Don't forget to clean up the database seeds: https://github.com/cubing/worldcubeassociation.org/blob/master/WcaOnRails/db/seeds/development/competitions.seeds.rb#L161-L180.
