### ISSUE TITLE
Schedule creation software

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#278]
Ilkyoo asked about this forever ago. Big competitions like US Nationals and Worlds are probably going to always want to build their own thing, but the WCA website should be able to provide all needs for smaller competitions. I think the only things missing right now are:
- [ ] Schedule
- [x] Map/travel information

**Comment by jfly** [comment]
Something recently raised by @SAuroux after finding 10 ocurrences of results that should have been records, but werent:

> All of those could have been found by running a script, since we ignored missing checkboxes that could only be resolved by checking a competition's schedule (calendar date rule), assuming that those have been handled correctly in the past. However, such a script would need to be quite complex to include all possible scenarios (like different competitions on the same weekend whose records affect each other).

I think that to improve this, we'd need to know the schedule of multiday competitions, which is something we could maybe start requiring delegates to enter.

**Comment by cubewhiz** [comment]
The schedule feature would be helpful for the WCA Board as well. When we confirm competitions, one of the things that we check is that the events list matches the schedule. Since schedules are done manually now, this usually means writing the events from the events list into notepad and then checking the schedule to make sure they all appear (and that there are no extras).
