### ISSUE TITLE
Registration requirements are shown when they are empty

### ISSUE THREAD

**Issue by Laura-O** [thewca/worldcubeassociation.org#2998]
The registration requirements for old competitions are shown even when they are empty:

![screenshot_2018-06-23_21-08-11](https://user-images.githubusercontent.com/362249/41812782-cd9be346-7729-11e8-9230-230cf626281b.png)
![screenshot_2018-06-23_21-08-48](https://user-images.githubusercontent.com/362249/41812783-cdc72650-7729-11e8-8719-804d76e1ebe1.png)

This was obviously already fixed in #2665, but seems to be broken again.

**Comment by jfly** [comment]
@viroulep, is this broken because we did a migration to add dummy registration requirements to all past competitions?

I think the best path forward might be to wait for @AlbertoPdRF's work in #2999 to go live, as that will make it so we no longer require registration requirements to be set for competitions. Then we can do another sql query to clear out registration requirements for old competitions that don't actually have requirements.

**Comment by viroulep** [comment]
Right, the requirements are not actually empty, but the field is set to "#", which appear empty.
(this was done in #2895)

I overlooked that this behavior would re-appear when modifying old competitions...

Fixing this would be easy, as we could just have a migration looking for "#" and changing it back to an empty string.

**Comment by jfly** [comment]
Hey Alberto, just be assigned this to you. Could you take care of this when you're done with your current work to revamp the registration requirements?

**Comment by AlbertoPdRF** [comment]
I will. Should I address this on a separate PR?

**Comment by jfly** [comment]
Yes, please don't do this in your current PR =)
