### ISSUE TITLE
Adding Competitions to Calendar

### ISSUE THREAD

**Issue by saranshgrover** [thewca/worldcubeassociation.org#3221]
As a calendar enthusiast, I always keep my calendar up to date with events. It would be really beneficial (and I don't think it's hard to implement) to add an option to add a Competition to someones calendar once they're registration has been approved.

**Comment by AlbertoPdRF** [comment]
Probably easy enough to deserve the good first issue label!

**Comment by jfly** [comment]
I'm going to remove the `good first issue` label here because I don't even know how to do this :/

@lgarron, I feel like you might have some experience here. Do you have any advice about how to do this? Do we have to generate different links for each type of calendar application people might use? (outlook, google calendar, apple calendar, ...?)

**Comment by AlbertoPdRF** [comment]
Yeah, maybe it's not a good first issue, but based on [this](http://dev.af83.io/2008/03/04/publishing-icalendar-events-with-ruby-on-rails.html) I didn't see it as something too difficult either -- maybe it's a good second issue? :slightly_smiling_face:

**Comment by dsoegijono** [comment]
I can look into this. Also, additionally, we can add .ics attachment to registration accepted emails?

**Comment by viroulep** [comment]
Fixed by #4672.

@dsoegijono I'm not sure it's strictly necessary, but it could be a nice addition; definitely feel free to take a look at it if you want!
