### ISSUE TITLE
Past competitions show up in "upcoming competitions"

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#3229]
https://www.worldcubeassociation.org/competitions

I see a few competitions including Asian Championship that have already happened in the "upcoming competitions" section.  The alt text on the hourglass says that it starts in "-2 days".

![screenshot from 2018-08-19 18-18-12](https://user-images.githubusercontent.com/3885929/44313793-580a4200-a3dc-11e8-9302-f6eaf163b0c6.png)

**Comment by jfly** [comment]
Here's the relevant code: https://github.com/jfly/worldcubeassociation.org/blob/702ffd97f43e6fc2973ac3c1bd117f4e317143e1/WcaOnRails/app/views/competitions/_index_competitions_list.html.erb#L19-L29, which roughly looks like this:

```ruby
in_progress_competitions, upcoming_competitions = competitions.partition(&:in_progress?)
unless in_progress_competitions.empty?
  # Render in progress competitions
end
unless upcoming_competitions.empty?
  # Render upcoming competitions
end
```

That `@competitions` array came from here https://github.com/jfly/worldcubeassociation.org/blob/702ffd97f43e6fc2973ac3c1bd117f4e317143e1/WcaOnRails/app/controllers/competitions_controller.rb#L91, which selects all competitions with `end_date >= Date.today`.

Here's our `in_progress?` method (https://github.com/jfly/worldcubeassociation.org/blob/702ffd97f43e6fc2973ac3c1bd117f4e317143e1/WcaOnRails/app/models/competition.rb#L695-L697):

```
def in_progress?
  !results_posted? && (start_date..end_date).cover?(Date.today)
end
```

I think the issue here is the `!results_posted` we have here (which I added in c0d1807db78f4bc0922258dfb0959c4a7f0e6fe6). This means that if you have a competition that ends today, but whose results are already posted, then we are treating it as an upcoming competition.

I'd argue that the bug here is with our `over` and `not_over` Competition model scopes. They are not consistent with the implementation of `in_progress`, which is smart enough to check if the competition is over.
