### ISSUE TITLE
Better error for Stripe payment failure

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#3448]
When something is wrong with the Stripe account linked to the competition by the organizers, the competitor can land on an impersonal 500 error from the server.

Here is the kind of error found in the log:

> Stripe::InvalidRequestError (This account cannot currently make live charges. If you are a customer trying to make a purchase, please contact the owner of this site. Your transaction has not been processed.)

We should absolutely catch this kind of errors and redirect the user to the payment form, with a clear message saying that there is something wrong with the Stripe account, that they have not been charged, and that they can't do anything about it (the problem has to be fixed by the organizers/WST).

**Comment by ligio90** [comment]
Hey, I'm gonna like look into this.

**Comment by jfly** [comment]
It looks like this just happened to 16 attempted registrations for Berkeley Spring 2019. We should definitely add handling of this exception to [`journaled_stripe_charge`](https://github.com/thewca/worldcubeassociation.org/blob/9c562820e11178b24a76bc79ba05804125d9ed97/WcaOnRails/app/controllers/registrations_controller.rb#L375).

For now, I'm going to update these 16 stripe charges as failed, because I know that they didn't go through.
