### ISSUE TITLE
Can't visit an unconfirmed competition's page with nil start/end dates

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#3532]
I noticed this while working on #3531.
Creating an unconfirmed competition with nil dates does work, but when rendering some of its views it may go at least through these methods:
  - [in_progress?](https://github.com/thewca/worldcubeassociation.org/blob/281f7b0e53501373011b9bbf6292ada159148cf4/WcaOnRails/app/models/competition.rb#L771) (which use a range with competition's dates)
  - [the schedule tab](https://github.com/thewca/worldcubeassociation.org/blob/281f7b0e53501373011b9bbf6292ada159148cf4/WcaOnRails/app/views/competitions/_competition_schedule_for_venue_table.html.erb#L8)

We should probably check these dates are not nil, or simply not allow competitions without dates :)

**Comment by jfly** [comment]
I don't have a strong opinion here, but it would be nice to fix this.

Requiring start and end dates might be the best option to avoid future bugs like this. If we do decide to require start and end dates, we should remember to go back and backfill this for past competitions with nil dates.

Alternatively, fixing the `in_progress?` method and schedule tab seem pretty simple!

I'm going to mark this as a good first issue. This isn't a great first issue because we haven't actually decided what to do yet, but either approach should be fairly simple to implement.

**Comment by ligio90** [comment]
I am working on this
