### ISSUE TITLE
Images are too big on results pages

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#3710]
Images in the "Information" section of competition pages become much larger when looking at results.

Example:
https://www.worldcubeassociation.org/competitions/NewJersey2018
https://www.worldcubeassociation.org/competitions/NewJersey2018/results/all

Compare the difference in the second page.

**Comment by UnsolvedCypher** [comment]
@cubewhiz This has been fixed, but images are still only limited by their width, not their height. You may want to size the image down before uploading it, particularly for tall images, since the width of the description area is still pretty large (I usually use about 300x300 for competitions).

**Comment by jfly** [comment]
We could also add a max-height restriction on images! Long term, maybe it would make sense for us to do some internal processing of images that are crazy large.

**Comment by UnsolvedCypher** [comment]
As of now, images are embedded via Markdown (usually from imgur) so they don't actually live on the WCA site. Would this processing require the images to be uploaded to the WCA site? That might actually be nice since less tech-savvy organizer may have trouble understanding that they need to upload the images externally and then embed.

I think it makes a lot of sense to limit the width to 100%, but it may be better to let the organizer decide how they want the height to look.

**Comment by AlbertoPdRF** [comment]
Kind of related: having images hosted externally means that eventually it's possible that they don't exist anymore, making competition pages lose important information like schedules and similar, which would be nice to keep for historical reasons.

**Comment by jfly** [comment]
Yeah, I don't like the idea of images being hosted on third parties. Rails 6 is hyping up [actiontext](https://weblog.rubyonrails.org/2018/10/3/introducing-action-text-for-rails-6/), which might be a good choice for us. I think it will integrate with ActiveStorage, and make it easy for us to support image uploads. I don't know if it's going to be the best tool for us, but I'm ok with waiting until Rails 6 comes out to revisit this.

**Comment by AlbertoPdRF** [comment]
That looks nice!
