### ISSUE TITLE
Should we enable refresh tokens for OAuth access?

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#374]
I don't even know this, and developers certainly won't know. This will probably require digging into [doorkeeper](https://github.com/doorkeeper-gem/doorkeeper) to figure out what it does, and then documenting it =)

**Comment by jfly** [comment]
Just did a little research on this. The access token you get from the WCA OAuth flow is only valid for 2 hours. Past that point, you either need to send the user through the WCA OAuth flow, or add support for refreshing access tokens to the WCA website. See https://github.com/doorkeeper-gem/doorkeeper/wiki/Customizing-Token-Expiration#access-token for a simple explanation of all this.

**Comment by timreyn** [comment]
I have a use case for refresh tokens.  For [CubingUSA Regional Championships](https://cubingusa.org/regional), competitors are only eligible to win regional titles if they live in a state in that region.  For example, because I live in Massachusetts, I'm eligible to win the Northeast regional title, but I'm not eligible to win the Southeast regional title.

The WCA doesn't know which states competitors live in; this is reported by competitors on the CubingUSA site.  Then we have our own [psych sheet](https://cubingusa.org/regional/psych/hl/2018#/) for each regional championship, limited to competitors eligible to win titles.  We'll use this list before the championship to make sure top competitors have their states selected, and during the competition to select the champions.

Right now, organizers of regional championships need to log in every few days and update the list of competitors.  It would be helpful to save a refresh token so that the organizer doesn't need to manually update the list every few days.
