### ISSUE TITLE
Add a "total amount paid" to the registrations table

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#3826]
(Tommaso Raposio (2014RAPO01) requested this in an email titled "Suggestion for Organizer View")

> I'm organising my third competition and for the first time I have noticed something that could help me and other organisers in the future. For the first time I was faced with some people not paying the registration fee because of agreements with venue owners and it was hard trying to remember everytime someone new registered how much money I had to work with. Will it be possible to add at the bottom of the "Paid" column in the "Approved Registration" table the total amount of money? (picture attached)

<img width="393" alt="example" src="https://user-images.githubusercontent.com/277474/51165882-79217280-1856-11e9-8628-d88fb8640e69.png">

I think this should be fairly straightforward to do, so I'm going to mark it as a good first issue.

**Comment by cubewhiz** [comment]
The amount paid won't be equal to the amount of money collected, though, due to Stripe fees. I suggest a note stating such is appropriate.

**Comment by priazz** [comment]
Hi,
Thank you for the consideration. Regarding what @cubewhiz said, couldn't you also simply deduct the fees before displaying the result instead of making a statement appear? Stripe fees are the same for people of the same region. For example in our case is very rare that people pay with non european cards so if there is a difference between money collected and amount paid it would surely be almost irrelevant.

Regards.
Tommaso Raposio

**Comment by ligio90** [comment]
I'm doing pair programming sessions with @jfly rn and I chose this as a first issue, so I guess its sudo-assigned to me? xd

**Comment by jfly** [comment]
Assigning to myself on behalf of @ligio90!

**Comment by ligio90** [comment]
Thanks :)
