### ISSUE TITLE
Remove confidential information from staging

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#3863]
**Describe the bug**
There are internal/sensitive documents and links that are accessible through the delegate/senior delegate panel on staging.

**To Reproduce**
1. Log into accounts with a board member/senior delegate.
2. Click on the delegate panel
3. Click on any link to a google doc external to a WCA site

**Expected behavior**
Not allowing people to see this stuff.

**Screenshots**
Any link below to a google doc is viewable by anyone who logs into my account on staging, as an example. This allows anyone to access forms for promoting delegates, or see internal documentation like the probationary policy.

![image](https://user-images.githubusercontent.com/6166412/51817635-60668300-2280-11e9-8180-2723c8d8194e.png)

Thanks to Sam Baird for pointing this out to me!

**Comment by viroulep** [comment]
Oh, I actually think the fix is not to restrict access to the links but rather fix the shared documents accessibility: the link are absolutely visible in this repository (see [here](https://github.com/thewca/worldcubeassociation.org/blob/7791f9f8058849914257d12b41aa40d8d88023e5/WcaOnRails/app/views/delegates_panel/index.html.erb#L17) for instance)!

@thewca/board, do you think it makes sense to just restrict access to mentioned documents?
I'd say Delegates + Board for the probationary status policy, and Seniors + Board for the Senior forms.

**Comment by EdHollingdale** [comment]
People also seem to be able to see all "Pending claims for your subordinate Delegates" and are thus able to admire my 0 outstanding WCA ID claims due to my lightning fast response time 😛 

I assume it is a breach of privacy to show if someone has/hasn't claimed an ID, plus we may not want anyone to see how responsive/unresponsive various delegates are.

**Comment by Jambrose777** [comment]
> Delegates + Board for the probationary status policy


And teams like wcat

**Comment by cubewhiz** [comment]
> Oh, I actually think the fix is not to restrict access to the links but rather fix the shared documents accessibility: the links are absolutely visible in this repository (see [here](https://github.com/thewca/worldcubeassociation.org/blob/7791f9f8058849914257d12b41aa40d8d88023e5/WcaOnRails/app/views/delegates_panel/index.html.erb#L17) for instance)!
> 
> @thewca/board, do you think it makes sense to just restrict access to mentioned documents?
> I'd say Delegates + Board for the probationary status policy, and Seniors + Board for the Senior forms.

I already had a draft in my email to the Board about changing the forms access. Now that all WCA users have @wca accounts, it is quite easy to make forms visible to the users we want without worry if the link is shared.

I'll take care of this on the Board's side to make sure the permissions are updated appropriately and then let you know here how we should update the panel.

**Comment by jfly** [comment]
> If we want to hide this information, we should probably set the delegate_id_to_handle_wca_id_claim to nil when dumping the database.

I am very slightly against this, in that it would make our developer database dump less representative of reality.

**Comment by cubewhiz** [comment]
The forms for nominations, promotions, demotions, etc. have been updated to require sign-in from a WCA account, so making their URLs public is no longer a problem. @AlbertoPdRF will submit a PR to update the Delegate panels.

**Comment by viroulep** [comment]
Fixed by #3898.
