### ISSUE TITLE
Adding "Multiple Countries" as an option in the Country drop-down

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#3869]
Multiple Countries without a specified continent(s) following it in parentheses is not currently an option.

Can we get "Multiple Countries" added as an option in the Country drop-down for competitions which will be happening across Earth simultaneously?

<img width="632" alt="multiple_countries" src="https://user-images.githubusercontent.com/45567122/52161687-3cb09c00-26c9-11e9-8929-f5c01cb0b138.PNG">

**Comment by jfly** [comment]
Sure thing, @c-goodyear. What's the timeline like on this? Is there a real need for this, or is this just for completeness?

**Comment by c-goodyear** [comment]
We hope to request WCAT for an announcement of such a competition in early
March. (The 9th is the current plan)

**Comment by viroulep** [comment]
I have just a bit of time now, I'll try to get this done.

**Comment by viroulep** [comment]
It's now deployed!

**Comment by cubewhiz** [comment]
Perhaps I don't realize it, but is there a good reason to keep Multiple Countries (specific place)? Wouldn't one "Multiple Countries" option be sufficient?

**Comment by jfly** [comment]
@cubewhiz, I think that have a single "Multiple Countries" would probably be fine, although might screw up some stats for people doing stuff like "number of continents competed in". I do want to get rid of the multiple country stuff eventually, see https://github.com/thewca/worldcubeassociation.org/issues/3355 for the start of a discussion about that. Short term, I think the simplest thing to do is to just keep following the existing pattern, as @viroulep has done here.

**Comment by viroulep** [comment]
Currently any "Multiple Countries" is tied to a real or fake continent, so having only one instance of it may lead to weird cases; such as selecting "Europe" in the continent list and not being able to see FMC Europe because for some reason we may have decided that the one "Multiple Countries" would be tied to the "Multiple continents" fake continent.

The only way to do this cleanly is to get rid of the "country" field of the competition, and introduce a "competition_countries" table that tells us precisely in which countries it takes place.

**Comment by cubewhiz** [comment]
@viroulep Indeed, that sounds like a much cleaner way to do it. Thanks for the clarification.
