### ISSUE TITLE
Show email addresses on registration tab

### ISSUE THREAD

**Issue by EdHollingdale** [thewca/worldcubeassociation.org#3934]
**Is your feature request related to a problem? Please describe.**
We get dozens of emails each week relating to competition registration (deletion, waiting list position, changing events etc.) and many of these do not mention the competitor name they are referring to. Often the name associated with the email is no good either, it could be a parent's name, or something like "Penguin Master Cuber". This then requires a back-of forth of emails for something that would otherwise be simple.

**Describe the solution you'd like**
Add the email address to the registration tab. Instead of the mailto button, just have the email address there! (Hyperlinked to a mailto link).

**Additional Benefits**
This will also give an easier check to WCA ID claims for delegates, and reduce the number of pages required to be visited if you want to verify a claim on mobile.

**Additional context**
How I would picture it:
![](https://i.imgur.com/rYxi1vS.png?1)

**Comment by ligio90** [comment]
would be good if you could toggle this (like the events) to make the screen a bit less congested if you don't want that.

**Comment by jfly** [comment]
Adding email addresses sounds like a good quickfix for the issue you've described here, @EdHollingdale. We've already been through one cycle of "oh my there are so many columns on this table it is both annoying *and* slow to load", which is why we added the toggle events button to hide a bunch of columns. I worry about us going down that same path if we just add columns willy nilly. Maybe we could get rid of a column that we think is not as useful as email address?

For a totally different approach: the WCT actually has a similar issue where people email them asking about some competition they've registered for, and they don't mention what competition they're talking about. They've asked for a "show me all the competitions a particular user is registered for" feature, see https://github.com/thewca/worldcubeassociation.org/issues/1723. If we build something like that, it might also be useful for the situation you're describing here.

**Comment by EdHollingdale** [comment]
I don't think the Birthdate column is as necessary anymore - especially since #3575 does the checking that it was used for. Having a "Show Birth Dates" button and showing emails by default could work? I also think moving the comments to the far right column of the table would be useful, since most of the time they are blank. It may also be worth noting that this doesn't technically _add_ a column - it just makes the mailto column significantly wider 😛 

In Australia all questions go to the support@speedcubing.org.au mailing list which means it can be quickly answered. This feature would mean we can quickly answer the "Please add 7x7x7 to my registration for Melbourne Spring"/"What is my waiting list position for Sydney Winter" emails, but the "Please remove pyraminx from my son's registration" emails would still require a bit more work. It would be good to have this combined with the WCT feature request as well! (and yes, a surprising number of emails are just one sentence requests, usually without a "thanks, [competitor name]" to help us out and with an unhelpful subject line like "competition question").

Depending on how the user search works, it is all well and good knowing the competition they are registered for and their name - but it may not immediately be linked to "edit their registration" (if you have appropriate permissions) and won't enable you to check additional information, such as their waiting list position.

**Comment by Jambrose777** [comment]
I would strongly disagree with removing the birthday column (even hiding it by default), if someone registers with a bogus birthday we should alert the delegate in any way possible not to accept the registration and fix the birthday before approving.

**Comment by EdHollingdale** [comment]
Shouldn't we automate the checking of Birthdates? Or provide an additional validation step when accepting the registration of a new competitor (correct name, birthdate etc.)? I haven't had any bogus birthdates since birthdates under 2 years old now get a warning at the registration step.

**Comment by UnsolvedCypher** [comment]
Not to take away from this issue, but @EdHollingdale you can enter the email address on the "Manage Users" page and it will bring up their account and name, making it much easier to find the person's registration. This solution still isn't perfect since we have no way to know what competition they're talking about, but if you can narrow it down to a few you can usually figure it out.

**Comment by EdHollingdale** [comment]
That is a good point that works for me @UnsolvedCypher but it would not work for people who are not delegates (e.g. organisers).

**Comment by ligio90** [comment]
I'm going to work on this
