### ISSUE TITLE
Competitions without Results

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#3970]
For competitions without results we should probably take measures to make the page look less broken.
https://www.worldcubeassociation.org/competitions/CaviteOpen22018#general-info
https://www.worldcubeassociation.org/competitions/PerryOpen2013

Ideally we'd have the left side not include the results tabs (as if results_posted_at was null) and then not display the warning message that pops up saying the competition results we come soon. Maybe just have an extra check if competitors = 0 then don't display these.

Another thing to consider is whether we want to keep other information (like the events, schedule) for the competition, which I think we do?

**Comment by jfly** [comment]
> not display the warning message that pops up saying the competition results we come soon

Where is this message right now? I don't see it.

**Comment by Jambrose777** [comment]
If you set results_posted_at to null on staging it will display this message, but not have result tabs.

**Comment by ligio90** [comment]
i will work on this.

**Comment by AlbertoPdRF** [comment]
I'm labeling this as a good first issue. By the way, do you still plan to work on this @ligio90? If yes, please assign yourself to the issue :)

**Comment by ligio90** [comment]
Yes I am buuuut since I am not in the wst i cannot assign myself any issues...

**Comment by AlbertoPdRF** [comment]
Ah, right, I just did! (Not without creating a bit of a mess first :stuck_out_tongue: )

**Comment by ligio90** [comment]
Alright, thanks!

**Comment by danieljames-dj** [comment]
@SAuroux filed this issue again, so I was just going through it. I've just tried to fix it as this looks inactive for nearly a year:

Add a function in `competition.rb`:
```
def results_available?
  results_posted? && !results.empty?
end
```

Then, I'll use `results_available?` instead of `results_posted?` [here](https://github.com/thewca/worldcubeassociation.org/blob/b4386218588b3f6ba954418d2240cdaf65cb5883/WcaOnRails/app/models/competition.rb#L982) and [here](https://github.com/thewca/worldcubeassociation.org/blob/b4386218588b3f6ba954418d2240cdaf65cb5883/WcaOnRails/app/views/competitions/_competition_info.html.erb#L173).

Is this change fine? If so, I can send a PR.
