### ISSUE TITLE
[Local] Mysql2 error on opening /competitions tab 

### ISSUE THREAD

**Issue by dsoegijono** [thewca/worldcubeassociation.org#4147]
**Describe the bug**
I've just set up the project locally, and ran into an issue opening the `/competitions` tab. Seems to be a SQL syntax error on `Event.official` scope:

> Mysql2::Error: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '< 990) ORDER BY `Events`.`rank` ASC' at line 1: SELECT `Events`.* FROM `Events` WHERE (rank < 990) ORDER BY `Events`.`rank` ASC

**To Reproduce**
1. Go to http://localhost:3000/competitions

**Expected behavior**
Show list of competitions.

**Screenshots**
![Screen Shot 2019-05-17 at 9 48 10 pm](https://user-images.githubusercontent.com/867840/57926115-c3425f80-78ed-11e9-95b6-27dc6f6b34b0.png)

**Desktop (please complete the following information):**
 - OS: macOS Mojave (10.14.4)
 - Browser: Safari 12.1, Chrome 74

**Additional context**
- mysql installed via `brew` (Ver 8.0.16)

**Comment by viroulep** [comment]
Sorry for the delayed response.
It's very much unexpected, and most likely has something to do with your local setup :s
When visiting the competitions page I can see the same SQL query issued and succeeding:
```
Event Load (0.2ms)  SELECT `Events`.* FROM `Events` WHERE (rank < 990) ORDER BY `Events`.`rank` ASC
```

As far as I know the production server (running Ubuntu) uses mysql 5.6.39:
```
mysql> select version();
+------------+
| version()  |
+------------+
| 5.6.39-log |
+------------+
```

Some other WST members and myself run Debian and use some version of MariaDB (10.1 for me).

This simple query works well:
```
MariaDB [wca_development]> select Events.* from Events where (rank < 900) order by Events.rank asc;
+--------+--------------------+------+--------+--------------------+
| id     | name               | rank | format | cellName           |
+--------+--------------------+------+--------+--------------------+
| 333    | 3x3x3 Cube         |   10 | time   | 3x3x3 Cube         |

```

Could you please do a "sanity check" by running the query directly in the SQL console?
You should be able to execute `mysql wca_development -u root` to connect to the db, then run `select Events.* from Events where (rank < 900) order by Events.rank asc;`.
If it succeeds then I don't get what's going on, if it fails it's consistent with the rails log but I'd have no idea where is comes from :p

My first guess would be the MySQL version (since you're running a newer version of it!), but I have no idea what kind of changes would lead such a basic query to not work :(

@tussosedan do you have any idea why such a basic query would fail in a newer version of mysql?

**Comment by dsoegijono** [comment]
Getting the same error on console:
```
mysql> select Events.* from Events where (rank < 900) order by Events.rank asc;
ERROR 1064 (42000): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '< 900) order by Events.rank asc' at line 1
```

However, if I changed it to this it works:
```
mysql> select * from Events where (Events.rank < 900) order by Events.rank asc;
```

**Comment by viroulep** [comment]
Ah I got it, 'rank' is a reserved keyword from 8.0 onward: [the doc](https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-8-0-detailed-R).

So
```sql
select Events.* from Events where (`rank` < 900) order by Events.rank asc;
```
should work (because `rank` is quoted).

Definitely sounds like a rails issue!

I'll look into reporting that (actually I'll look into a potential easy fix before reporting).
But yeah so far your only option is to not use mysql 8 :s

**Comment by viroulep** [comment]
Never mind that's on us :)

Given it's an issue on our side, I wouldn't mind you staying on mysql 8, just in case you run into any more issues that would be blocking in case we update to mysql 8 some day!
(yes, it does mean that if something is wrong, you'll be the first impacted :s)

**Comment by dsoegijono** [comment]
👍 That's great! Saves me the trouble of downgrading ;) Definitely don't mind getting impacted by issues. Might finally learn mysql!

**Comment by tussosedan** [comment]
Ha, I was just going to post the same link to the new keywords, but @viroulep beat me to it by 10 minutes :) mysql error messages aren't that great.
