### ISSUE TITLE
My Competitions and My Results under User

### ISSUE THREAD

**Issue by dsoegijono** [thewca/worldcubeassociation.org#4158]
**Is your feature request related to a problem? Please describe.**
I always instinctively go to user navigation to find my competitions or results. Even though they make sense where they currently are, I think it's a more common pattern to have user specific information under user nav.

**Describe the solution you'd like**
Add "My Competitions" and "My Results" links under User nav.

**Comment by EdHollingdale** [comment]
I agree that My Results could go in the user navigation. However I am very used to My Competitions being exactly where it is - I visit it ~20 times per day to do registration checks for multiple competitions, and I don't like change 😛 At least in my head it being under competitions makes sense, but that it more because I approach them "Competitions that I am managing" rather than "competitions that I am attending" which feels less of a user-specific thing. I appreciate that non-delegates/large scale organisers use my competitions very differently to me.

**Comment by dsoegijono** [comment]
> because I approach them "Competitions that I am managing" rather than "competitions that I am attending" which feels less of a user-specific thing

That makes sense! I definitely came from a competitor only, non-delegate point of view so I saw it as more user specific. One way we can get around this is maybe to *add* it to User nav instead of *move*, so both navs would have them. Not sure how everyone feels about duplicated navigations though.

**Comment by cubewhiz** [comment]
I think adding it makes sense. Some stuff is already duplicated (example: "New competition" is under the Competitions tab and the User nav.

**Comment by AlbertoPdRF** [comment]
+1 to add it under User instead of just moving it. I'm labeling this one as a good first issue!

**Comment by Rubiks-boy** [comment]
Hello! I'd like to try this out if that's ok! I already have my environment set up (able to visit the site on localhost:3000).

**Comment by AlbertoPdRF** [comment]
Hi @Rubiks-boy, that's great news!

I've just assigned you to the issue and I'm going to review your PR now :slightly_smiling_face:
