### ISSUE TITLE
Gender: Change 'other' to 'prefer not to say'

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#4361]
After an email conversation with many people, the current options we provide for gender are not correct.

From what I understood (I'll like this issue to the email thread so other parties can correct me if wrong), other and prefer not to say are two vastly different things. Importantly, other does not encompass prefer not to say. The preferred option would be to have a 4th specification of 'prefer not to say', however there are issues with this as there are people currently listed as 'other' that are in both categories.

If i'm not mistaken, 'prefer not to say' can include 'other'. So changing any terminology on the website that lists the gender option as 'other' to 'prefer not to say' can help correct this issue.

**Comment by Jambrose777** [comment]
To go along with this. If they can't already, competitors should be given the option to register with the prefer not to say option.

**Comment by cubewhiz** [comment]
I don't agree that 'prefer not to say' includes 'other'. I'd rather keep the four options.

If there is an overlap in which some of the people who selected 'other' may have chosen it to mean 'prefer not to say', perhaps we can just reach out to each of them and give them the option to switch. Is the number of such users small enough to manage this?

**Comment by cubewhiz** [comment]
Alternatively, we could use three options: male, female, and other/prefer not to say. This would allow the third option to include both.

**Comment by Jambrose777** [comment]
52 people have gender other currently.

**Comment by cubewhiz** [comment]
That's pretty small. I think we could email them give them the choice to switch if we decide to have 4 options.

**Comment by jonatanklosko** [comment]
> 52 people have gender other currently.

Note: there are 603 such **users**, and they would be affected by those changes as well.

**Comment by cubewhiz** [comment]
Are users able to change their gender after it has been set? I'm asking about both users with and without a WCA ID.

**Comment by jfly** [comment]
For the record, we actually have two tables for storing user data ([`users` and `Persons`](https://github.com/thewca/worldcubeassociation.org/wiki/Why-do-we-have-both-%22users%22-and-%22persons%22%3F)). It's pretty easy for us to change what goes into `users` because the logic for that is captured entirely in the WcaOnRails repository. `Persons` is quite a bit more complicated, because it goes through the whole results posting flow:

1. Competition organizer sets up registration for the competition on some website. If this website is the WCA website, great, we have control over that. If the website is some other website, then we don't have a lot of control over how that behaves. @cubewhiz is very familiar with this problem, and is one of the reasons why we'd like to (eventually) force all registration to happen on the WCA website.
2. Registration data gets downloaded to a CSV and uploaded to a competition results manager tool (such as cubecomps). The WST does now control cubecomps, but it is effort for us to update, because none us really know the codebase.
   - Note: There's also sometimes registration at the door (walkins)!
3. Results get downloaded as an excel file and run through the WCA workbook assistant.
4. The results get exported from the WCA workbook assistant as a JSON file and uploaded to the WCA website, at which point they get run through the administrative scripts the results team uses.

We'd need to validate that the right thing happens at every link in this chain.

From the perspective of the `users` table, we actually support 4 genders (male, female, other, and "the WCA does not know"):

```sql
mysql> SELECT DISTINCT(gender) FROM users;
+--------+
| gender |
+--------+
| m      |
| NULL   |
| f      |
| o      |
+--------+
4 rows in set (0.36 sec)
```

Here's how the `Persons` table looks (I'm not actually sure what `NULL` and empty string mean here):

```sql
mysql> SELECT DISTINCT(gender) FROM Persons;
+--------+
| gender |
+--------+
| m      |
| f      |
| NULL   |
| o      |
|        |
+--------+
5 rows in set (0.26 sec)
```

> Are users able to change their gender after it has been set? I'm asking about both users with and without a WCA ID.

Users with a WCA ID cannot change their gender, they'd have to contact the WRT.
Users without a WCA ID can change their gender.

> If there is an overlap in which some of the people who selected 'other' may have chosen it to mean 'prefer not to say', perhaps we can just reach out to each of them and give them the option to switch. Is the number of such users small enough to manage this?

Another option might be to NULL-ify their gender (aka: change it to "the wca doesn't know"), and then send every affected person an email saying "hey, sorry we did this, we weren't sure what you actually wanted this to be".

Also relevant: https://github.com/thewca/worldcubeassociation.org/pull/1542

**Comment by SAuroux** [comment]
May I ask why 'prefer not to say' should even be a valid option? [Regulation 2c](https://www.worldcubeassociation.org/regulations/#2c) requires competitors to provide this information. 

However, we are already very liberal regarding gender and allow everyone to make a reasonable choice for their gender. We are always happy to change recorded genders for legal males identifying as female and for legal females identifying as male. Likewise, we are also happy to accept 'other' in cases where people simply prefer not to say or just prefer to not subscribe to the concept of gender classes.

Overall, I am strongly against any change of the current classes and would rather like to see gender information completely removed than coming up with more classes.

**Comment by c-goodyear** [comment]
Currently we are collecting gender with no legal reason or basis to do so. Since we don't recognise Male rankings, Female rankings, or anything of the sort it's basically requiring a data point from every member because we could.

The option to remove gender information completely would probably be the best option, however there are the plans in place from [#1919](https://github.com/thewca/worldcubeassociation.org/issues/1919) which this would affect.

Having the "prefer not to say" option also allows competitors some safety if they are from regions where "other" would be a very contentious (and sometimes dangerous) choice.

**Comment by suushiemaniac** [comment]
@c-goodyear In those places where "other" is a dangerous choice the "prefer not to say" option would be equally contentious, because it very directly implies "I have to hide something" (from the viewpoint of those bastards who prosecute LGBT…)

**Comment by Rubiks-boy** [comment]
Hi, 

I noticed the registration page still lists "Male", "Female", and "Other", so bumping this thread from a while ago. 

Now that Cubecomps is out of the picture and a majority of registrations take place through the WCA site, does this make it easier to add "Prefer not to say" as an option? If not, it feels like @cubewhiz's suggestion of changing "Other" to "Other/Prefer not to say" would at least be a step in the right direction.

In response to users able to change their gender after it has been set: Would it be possible to allow users to change their gender in the database, even if a WCA ID is linked? In an ideal world, it feels like emails for this shouldn't be necessary.

I'm also curious if optionally asking for pronouns instead of gender might be both more inclusive and/or more useful.

**Comment by c-goodyear** [comment]
Cubecomps does not affect this.

> In response to users able to change their gender after it has been set: Would it be possible to allow users to change their gender in the database, even if a WCA ID is linked? In an ideal world, it feels like emails for this shouldn't be necessary.

Considering this is something that is quite a rare occurance, and could be open to trolling/abuse if left open to user change I think that the current system with emailing the WRT is fine. Even more so considering that gender rankings are now displayed on the website. In future we may have to be less liberal (as Sébastien put it) about how people select their gender - multiple ways the WCA could move forward could entail restrictions on having members legal gender registered, not just one they choose.

> I'm also curious if optionally asking for pronouns instead of gender might be both more inclusive and/or more useful.

If someone wants to be called something other than what people are currently calling them that is best addressed at the local (in this case, competition) level, not a database/infrastructure level.

**Comment by zeecho** [comment]
Maybe dumb and off-topic question but why do we store genders at all in the first place? Wouldn't getting rid of them be the easiest? I know gender rankings were added a few days ago but I think these rankings make no sense as we do not recognise gender records anyway (and I'm really glad we don't!). All in all, I think gender is a personal data which is both controversial (worldwide) and unneeded (at least for our sport). Therefore, what are the arguments for keeping these data in the database? Would we have issues if we removed them? (I'm asking from a general point of view as I'm pretty sure it's technically easy)

**Comment by Jambrose777** [comment]
> Maybe dumb and off-topic question but why do we store genders at all in the first place? Wouldn't getting rid of them be the easiest? I know gender rankings were added a few days ago but I think these rankings make no sense as we do not recognise gender records anyway (and I'm really glad we don't!). All in all, I think gender is a personal data which is both controversial (worldwide) and unneeded (at least for our sport). Therefore, what are the arguments in favour of keeping these data in the database? Would we have issues if we removed them? (I'm asking from a general point of view as I'm pretty sure it's technically easy)

Here’s a few reasons:
- having someone associated with a gender allows us to be able to look up what pronouns they prefer (he/she/they) for use in emails or at competitions
- gender is used by some competitions for gender awards
- it’s important for us to look at gender ratios overtime. We already have a staggering male:female ratio and if it gets worse and worse wca should be asking why.

**Comment by Jambrose777** [comment]
I'm going to close this for now since its pretty controversial, and keep the 3 options Male, Female and other with NULL for missing genders. If we want to revisit this someday we can.

**Comment by denthebro** [comment]
This conversation actually got me thinking about why the WCA even needs to store gender information. It's not like speedcubing is an athletic sport where there's an unfair advantage towards any gender.

**Comment by Jambrose777** [comment]
> This conversation actually got me thinking about why the WCA even needs to store gender information. It's not like speedcubing is an athletic sport where there's an unfair advantage towards any gender.

I listed a couple reasons 2 messages above. Another is we now have gender rankings on the website.

**Comment by denthebro** [comment]
> 
> 
> > This conversation actually got me thinking about why the WCA even needs to store gender information. It's not like speedcubing is an athletic sport where there's an unfair advantage towards any gender.
> 
> I listed a couple reasons 2 messages above. Another is we now have gender rankings on the website.

Oh, I'm sorry. I didn't realize we even had those rankings. I think male, female and other should be fine. Maybe we can email the competitors with "other" and ask for their opinion?
