### ISSUE TITLE
Armenia should be listed as Europe not Asia

### ISSUE THREAD

**Issue by Mollerz** [thewca/worldcubeassociation.org#4390]
Plenty of research points to the fact that they should bit listed as Europe and not Asia. Not sure how to do the PR for this as I know there are 3 files that need to be changed based on the last continent change (Trinidad and Tobago).

**Comment by viroulep** [comment]
Could you please create the issue on the Regulations repository?
Since they are in charge of maintaining the states file, and we seed our db from this file, the only actual fix needed is there :)

Once it's fixed there, we just need to update the generated json file and run a migration to update our countries data!

**Comment by viroulep** [comment]
Oh and for the record #2907 describes what I did last time we updated the states file.
I'm pretty sure we could also avoid the migration and just manually update the db, since for later db seeding the data will be up to date.
