### ISSUE TITLE
Notify me when someone registers checkbox errors when less than 28 days before the competition

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#4673]
I (and other organizers) can't change 'Notify me by email when someone registers for this competition' checkbox in competition less that in 28 days.
![image](https://user-images.githubusercontent.com/18090165/65997293-c5264d00-e4a1-11e9-98b7-fed15a874ef8.png)

**Comment by EdHollingdale** [comment]
What would be better is to have a global option to unselect the tick-box by default. I don't think anyone actually wants to receive all those emails!

**Comment by AlexKatyukov** [comment]
Ahah, I always say "don't forget" to organizes. 2:14, 2 октября 2019 г., "Edward Hollingdale" <notifications@github.com>:What would be better is to have a global option to unselect the tick-box by default. I don't think anyone actually wants to receive all those emails!

**Comment by zeecho** [comment]
> What would be better is to have a global option to unselect the tick-box by default. I don't think anyone actually wants to receive all those emails!

Well, I do :p It helps me to easily see if organisers are thinking about handling registrations or not and to know which registrations still need to be taken care of

**Comment by EdHollingdale** [comment]
Ping again to have a global option to not receive these emails, or to **disable them by default**. For reference, if you add up the registrations for Australian competitions managed through the WCA website it is over 3500 in the last year. We do not want to receive these!!!

**Comment by viroulep** [comment]
The current way the option is handled is very disturbing: it's an option on the competition edit page but it's actually a per-user option.
I'd also support moving it out to the user preferences (even if this means we have to drop the "per-competition" setting).

@edhollingdale it's not gonna make you much happier, but you can definitely filter them based on the subject and auto-archive them until this is implemented :s

**Comment by KerrieJarman** [comment]
Ping again on this bug - I have a competition opening today with 180 competitors and stupidly forgot to turn it off and now it is too late! For the Speedcubing Australia account (that is set as an organiser on all Australian competitions) we NEVER want emails turned on.  There needs to be a way to turn it off by default.

**Comment by Jambrose777** [comment]
Not that this matters, but Since the start of 2019, a majority of people have had this checkbox checked (but that might just be due to it being the default option):
![image](https://user-images.githubusercontent.com/11577241/122624844-18727180-d070-11eb-8ef6-535c65f8a863.png)

So I wouldn't change the default, but I definitely think it should be moved to a user preferences page.

**Comment by denthebro** [comment]
> 
> 
> Not that this matters, but Since the start of 2019, a majority of people have had this checkbox checked (but that might just be due to it being the default option):
> ![image](https://user-images.githubusercontent.com/11577241/122624844-18727180-d070-11eb-8ef6-535c65f8a863.png)
> 
> So I wouldn't change the default, but I definitely think it should be moved to a user preferences page.

I'm almost certain that's why

**Comment by viroulep** [comment]
Assigning myself since I plan to submit two fixes:
  - one to allow organizers/delegates to update the notifications checkbox even when we're less than 28 days away from the competition.
  - one to actually implement a per-user default setting, because a couple of delegates (including myself) actually miss the old default and some complained on the staff mailing list.
