### ISSUE TITLE
"You've been added as an organizer" email sent out in wrong language

### ISSUE THREAD

**Issue by sarahstrong314** [thewca/worldcubeassociation.org#4687]
These emails get sent out in the language that the person who created the competition page has their WCA account set to, rather than the language the email recipients have their accounts set to.

Here's an example. The email got sent out to all the organizers in Italian, which is the language I have my WCA account set to. 

![Screenshot 2019-10-05 21 24 02](https://user-images.githubusercontent.com/5139750/66262879-15a9ed00-e7b7-11e9-8f79-5d6e01e600d0.png)

**Comment by viroulep** [comment]
For all the emails in [this range](https://github.com/thewca/worldcubeassociation.org/blob/0ff5fc92a44f4ba48abb56ebcb17461896c8044c/WcaOnRails/app/mailers/competitions_mailer.rb#L48-L68), the localized_email should actually use the `organizer.preferred_locale` or default to `:en` if nil.
For all the emails in [this range](https://github.com/thewca/worldcubeassociation.org/blob/0ff5fc92a44f4ba48abb56ebcb17461896c8044c/WcaOnRails/app/mailers/competitions_mailer.rb#L22-L46), the localized_email should use `:en` since all the organizers are in copy.

This is a fairly easy first issue for a new contributor.

**Comment by Claster** [comment]
Btw, comments sent from the contact form (e.g. about competitions) are also sent in the language of the sender rather than the recipient. Not that it bothers that much though, as there are only words like "name", "email", "comment" and so on.

**Comment by tussosedan** [comment]
I'll take a look at this one.

**Comment by tussosedan** [comment]
@viroulep what if all the organizers have the same non-English locale? Would we want to use their common locale instead of :en?

Or we could do it like in the "notify_organizer" cases, where the controller loops over each organizer and sends a separate mail -- unless this needs to be a single group mail?

Not that I object to the easy solution, just making sure the flow is correct :)

**Comment by viroulep** [comment]
Hum, I definitely don't mind such a neat optimization (ie: checking if everyone shares a locale).
But I think your suggestion of splitting the email (one localized per organizer) makes sense too!
I don't think these threads (the confirmation email and announcement email) are used for discussions, so we may as well send N localized notification emails.
@DanielEgdal do you have an opinion on this?

**Comment by tussosedan** [comment]
@Claster I looked into the contact form email as well, and as it's sent to both the user and the WCA address(es), in my opinion it's more customer-centric to use the user's locale. Leaving it up to @viroulep to decide :)

**Comment by DanielEgdal** [comment]
The emails organizers receive about being added as an organizer and the announcement post does not have any official usage. (WCAT only communicates via the Delegate on the submission thread except in extreme cases). 
So like Philippe mentioned, it would make sense to just send out these mails one at a time to the organizer in their local.

**Comment by tussosedan** [comment]
@DanielEgdal the submission thread is the `"%{delegate_name} confirmed %{competition}"` email? So that one should stay addressed to all the organizers together? (`Dear organizers of %{competition}, Your competition Delegate %{delegate_name} confirmed %{competition} and sent the submission to the WCAT` etc.0

**Comment by viroulep** [comment]
No, the submission thread is the email sent to both Delegates and the WCAT, organizers are not in copy  (the "notify_wcat_*").
The emails to organizers can be split in multiple ones.
