### ISSUE TITLE
Make Regional Delegate status visible

### ISSUE THREAD

**Issue by Ivan-Brigidano** [thewca/worldcubeassociation.org#4851]
Now there is now way of knowing who is the Regional Delegate of a region just by looking at the [Delegates list](https://www.worldcubeassociation.org/delegates).

**Comment by Jambrose777** [comment]
https://github.com/thewca/worldcubeassociation.org/issues/4222

Unfortunately I don’t have much time to work on it and I haven’t gotten much help since Alberto left

**Comment by viroulep** [comment]
@moralsh talked to me about revisiting the Delegates page (from a purely visual point of view, not the internal stuff Jacob has been working on).

**Comment by moralsh** [comment]
Yeah, That page needs to be adapted to Jacob's work, I'll be on holidays for a week, but after that I'll be happy to help.

**Comment by cubewhiz** [comment]
This came up in the Board's meeting today--it is difficult to keep track of who the Regional Delegates are, especially because they are not identified anywhere.

It looks like the Delegate Table overhaul isn't happening soon. Would it be possible to at least create this category on the website so that we can store this? For now, it is fine even if the Regional Delegates are treated like Delegates with regards to permissions, etc.

**Comment by coder13** [comment]
Should this essentially be done the same as it is for senior delegate?

Have all delegates have a "region delegate" and add region_delegate as a delegate status?

**Comment by gregorbg** [comment]
@coder13 We have #5417 in the works which aims to include Regional Delegates.
Instead of a makeshift solution, I am still strongly in favor of implementing the proper rewrite. It is also high on our monthly priority list.

**Comment by danieljames-dj** [comment]
Regional Delegates is live now and hence closing this issue.
