### ISSUE TITLE
Implement Trainee Delegates

### ISSUE THREAD

**Issue by cubewhiz** [thewca/worldcubeassociation.org#5118]
Following the passage of the Motions, we will need to crate a new Delegate role for Trainee Delegates.

They should have the following rights on the website:
- to be listed as a Delegate for WCA Competitions (only if another non-Trainee Delegate is also listed)
- to read and participate in Delegate reports
- to participate in writing Delegate reports (but not be able to submit)

While we wait for a restructured Delegates table, I wonder if it makes sense to create this as a "team" for now. I do not think Trainee Delegates should be listed on the website as they are not WCA Staff (or if they are, it should not be integrated in the table of Delegates).

**Comment by maconard** [comment]
I'd just like to present a user interface idea for implementing this:

In the Organizer View edit screen of a competition where delegates/organizers are selected, we could put a similar box between WCA Delegates and Organizers called Trainee Delegates that is grayed out until at least one Delegate has been set in the WCA Delegates selector. 

Then trainees aren't mixed in the results with regular delegates, and it's fairly clear that trainees are being added second to work with the primary delegate(s). This would also need one catch to not allow a lone WCA Delegate to be de-selected while the trainee box is filled.

![trainee_selector](https://user-images.githubusercontent.com/31703304/73977132-bdffc780-48f7-11ea-8755-5e84a101b643.png)
(image is easier to read if you click it)

This could also be hidden until a checkbox "Allow adding Trainee Delegates to this competition" is selected, if people think it's too much space in general (as most comps may not have any trainees for some time).

**Comment by cubewhiz** [comment]
I like that. I don't think it needs to be hidden on the Organizer page.

**Comment by viroulep** [comment]
A few comments and hopefully useful hints:
  - It's not clear what would be best between adding a team and adding an extra status in our delegate_status enum. Adding an element to the enum would require to adjust our `staff?` method which consider staff anyone who is any kind of delegates. But besides that, adding trainee as a delegate status pretty much avoid any other change regarding access right.
  - if we go the new status way, on the WCA Delegates page we can filter out trainees
  - I guess the UI Michael described makes sense, on the server side the changes needed would be to validate the inclusion of the delegates field in all but trainee status, and for the field they would need to be trainee only. We may need to adjust the javascript and our user API to be able to filter users based on trainee delegate status.

**Comment by KitClement** [comment]
Should trainee delegates also have the ability to work with results? Or are we leaving the submission to the main delegates? Will trainees have access to the scrambles matcher and WCA Live results within that when listed as a trainee?

**Comment by SAuroux** [comment]
@KitClement In my understanding the answer to all of your questions is yes. Trainee delegates should have the ability to work with results and prepare the result submission, but ultimately confirming the submission and verifying the tranee delegates' work is up to the main delegates.

**Comment by cubewhiz** [comment]
Since the Trainee will only prepare the submission, but the Delegate actually submits the results, I don't think any change is necessary in the software. As far as I know, the Scrambles Matcher can be accessed by anyone and WCA Lives results can be managed in the Admin of the competition.

**Comment by EdHollingdale** [comment]
On that note then an extension would be to let trainee delegates admin competitions they are listed as a trainee for on WCA Live.

**Comment by SAuroux** [comment]
> Since the Trainee will only prepare the submission, but the Delegate actually submits the results, I don't think any change is necessary in the software. As far as I know, the Scrambles Matcher can be accessed by anyone and WCA Lives results can be managed in the Admin of the competition.

That is very obviously a half-baked approach though. Clearly, Uploading a JSON, rectifying possible errors and writing comments for WRT are also part of preparing the result submission. 

Both of these tasks (preparing report, preparing result submission) should just work for trainee delegates like preparing a competition works for organizers: you can prepare everything, but only the competition delegate can confirm (=submit).

**Comment by danieljames-dj** [comment]
Did anybody already start working on this? Else, I would like to give a try.

**Comment by viroulep** [comment]
Definitely feel free to do so!

I think the UI suggested looks good, so here are a couple of pointers to internal information which may be useful:
  - to store the trainees associated to competitions, you'll need to add a new table. Such actions is performed through [rails migrations](https://edgeguides.rubyonrails.org/active_record_migrations.html).
You can have a look at the one which introduced `competition_delegates` [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/db/migrate/20150718020123_create_competition_delegates.rb).
  - to make this table exist in the rails world, you need to create a model (see [here](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/competition_delegate.rb) for the competition_delegates one).
  - to actually make the link between competitions and their trainees in the rails world, you need to declare an association with it, similarly to what is done [here](https://github.com/thewca/worldcubeassociation.org/blob/440640bac8ce6a0b171207f36ae4c1f10b921a13/WcaOnRails/app/models/competition.rb#L16-L17).
  - because trainees are not staff, you will probably have to change the [`user.staff?`](https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/models/user.rb#L519) method to use some new `delegate_not_trainee?`.
  - to ease the filtering in the API, you will want to introduce a `trainee_delegate?` method next to the ones above
  - we use a custom input for delegates, by passing "only_delegates" to our custom [user_ids_input](https://github.com/thewca/worldcubeassociation.org/blob/2f2a1b591a64fcef5cfb5ad7e0ee01a1e61f4e21/WcaOnRails/app/inputs/user_ids_input.rb). You'll probably want to add an "only_trainees"; you can find out the relevant places by looking for [`only_delegates`](https://github.com/thewca/worldcubeassociation.org/search?q=only_delegates&unscoped_q=only_delegates).
  - the API uses the user search method [here](https://github.com/thewca/worldcubeassociation.org/blob/2f2a1b591a64fcef5cfb5ad7e0ee01a1e61f4e21/WcaOnRails/app/models/user.rb#L670-L689). This is where you want to change the existing "only_delegates" param to only look for non trainees Delegates, and introduce the "only_trainees" that will look specifically for these.
  - then there are a few UI/controller check to tweak (confirming a competition, submitting results, submitting the report), so that they check for a delegate not trainee status.

I think I've covered pretty much all the changes required, you will probably have to add new tests and/or modify existing ones for these changes!

**Comment by cubewhiz** [comment]
> > Since the Trainee will only prepare the submission, but the Delegate actually submits the results, I don't think any change is necessary in the software. As far as I know, the Scrambles Matcher can be accessed by anyone and WCA Lives results can be managed in the Admin of the competition.
> 
> That is very obviously a half-baked approach though. Clearly, Uploading a JSON, rectifying possible errors and writing comments for WRT are also part of preparing the result submission.
> 
> Both of these tasks (preparing report, preparing result submission) should just work for trainee delegates like preparing a competition works for organizers: you can prepare everything, but only the competition delegate can confirm (=submit).

Fair enough!

**Comment by danieljames-dj** [comment]
Hi, so I started working on it and actually stuck in between. I'll explain my first stage plan (Philippe's information really helped, thanks for that):

**1. Create a table for trainee_delegate**
For this, I ran the following in terminal:
`bin/rails generate model Delegate user_id:integer status:string start_date:date end_date:date`
(in my system, I named the model as TempaDelegate expecting that I've to change it again)
I got this table structure from Jacob's [comment](https://github.com/thewca/worldcubeassociation.org/issues/4222#issuecomment-508364756) in [issue 4222](https://github.com/thewca/worldcubeassociation.org/issues/4222).
My plan is to use this table for trainee delegate alone, but I named it as 'Delegate' because in future, this can be used for all delegates as well as discussed in that issue.

**2. Add a person to Delegate table if he is assigned as a Trainee delegate in edit user page**
When the senior changes the status from empty to trainee, I'll add a row in Delegates table with `start_date` as the present date in server and `end_date` as `null`. Later, when the senior changes it to junior delegate, `end_date` will be marked as then present date and `delegate_status` in `users` will be changed from `null`/<empty> to 'Junior Delegate'.

**3. Add trainee delegate in competition edit page**
Just the same way as the UI implemented above.

After 3, I've the report,  results thing, I'll check that once these 3 are done.

I'm done with 1. 3 should be pretty easy. But I couldn't do 2. Can someone point out a similar thing where something like 2 is implemented, so that I can check that and understand?

I'll just show something I did:
`edit.html.erb`:
```
<%= f.input :tempa_delegate, label: "Delegate Status", disabled: !editable_fields.include?(:senior_delegate_id) do %>
            <%= f.select :tempa_delegate, options_for_select(@user.temp_delegate_status_name), { include_blank: "" }, { class: "form-control main-event" } %>
          <% end %>
```

`user.rb`
```
def temp_delegate_status_name
    {
      trainee_delegate: "trainee_delegate",
      trainee_delegatea: "trainee_delegatea",
      trainee_delegateb: "trainee_delegateb",
    }
  end

  def temp_delegate_status
  end
```

```
before_save :save_delegate_status
  def save_delegate_status
    puts(tempa_delegate)
  end
```

**Comment by viroulep** [comment]
It sounds like you're trying to address two issues with your PR (introducing trainee delegates and solving the issue of time frames for delegates status), I think it would be best for you (and us as reviewers) to keep your changes in the scope of that particular issue.
In particular implementing time frame for Delegate status would open a box with a lot of stuff, I welcome you to do that after this is done, but please don't do it now :p

So you don't need to create a separate table for trainee delegates just yet (that is achieved by adding a new entry in the delegate_status enum), just a new table to make the association between a competition and a trainee delegate.

However I can reply to your question, although it's probably not relevant anymore: to avoid submitting arbitrary attributes for models, we actually use a whiteliste of possible attributes in the controller.
This is done in the [`competition_params`](https://github.com/thewca/worldcubeassociation.org/blob/8ffc9f85a0662be604ff05696dde4b3770684352/WcaOnRails/app/controllers/competitions_controller.rb#L503-L572) method, which creates an array of allowed attributes based on the competition's status and user editing the competition.

Also, when creating a model which has attributes "foo" and "bar" stored in the db, you don't actually need to create these methods in the rails model, they are created automatically for you :)

**Comment by danieljames-dj** [comment]
Hi Philippe, yes I was trying to do two issues as you said. Sorry for that ^_^ I'll concentrate on this alone for now as you said. And as you said, that is easier for me to learn as well. I'll definitely be happy to take up the other issue after this.

I've implemented two things so far and to be frank, I didn't understand what I did not understand a few things that I wrote. I just copy-pasted from similar things. I'll list out a few of my doubts in both of them:

1. Making a registered cuber a trainee delegate
My code can be seen [here](https://github.com/danieljames-dj/worldcubeassociation.org/commit/d960f1f7e0b766500fd3083657574d7c96aa2929)
Doubts:
1.1. I've added `trainee_delegate: true` in users.js, but I am not to able to find how it is getting connected to `edit.html.erb`.
1.2. I've added the same in `delegate_status_requires_senior_delegate` of `users.rb` as well. Is it really needed to add there as well? Because I'm not getting how it's called.

Note: For `any_kind_of_delegate`, I'm not considering Trainee Delegates because Trainee Delegates actually don't have many powers of a normal delegate.

2. Adding a trainee delegate to a competition
My code can be seen [here](https://github.com/danieljames-dj/worldcubeassociation.org/commit/bc4607992fcfb0ee6e71d1ddb04a9f068f2c8bd8)
Doubts:
2.1. I've added `trainee_delegate_ids` to `permitted_competition_params` in `competitions_controller.rb`. Does it mean that whatever I add to `permitted_competition_params` will be stored to the database?
2.2. I've created the model & table using `bin/rails generate model CompetitionTraineeDelegate competition_id:string:index trainee_delegate_id:integer:index` and copied the contents from CompetitionDelegate model. Is this the right way?
I've few other doubts as well, but I think if I'm clear with the above things, I'll be able to understand others myself.

**Comment by viroulep** [comment]
> Note: For any_kind_of_delegate, I'm not considering Trainee Delegates because Trainee Delegates actually don't have many powers of a normal delegate.

Actually I think it's simpler to consider them as Delegates, as we do want them to upload results and write reports.
We just don't want them to do the last final click on "confirm" or "submit result".

In which case you can leave most of the right management as is, and only check for a non-trainee Delegate for the sensitive actions.

**Comment by danieljames-dj** [comment]
Thanks a lot Philippe. I did it as you said and I'm done with the feature implementation I think (not sure if I missed any use-cases). I'm now writing the test cases, but I'm stuck. I've posted my doubt in the [PR](https://github.com/thewca/worldcubeassociation.org/pull/5249#issuecomment-598779274).

**Comment by viroulep** [comment]
It's worth noting that I also did suggest to add an entry to the existing enum earlier in the thread ;)

I obviously can't recall exactly my thought process, but most likely I initially thought trainees would have the same right as other delegates, which turned out not to be the case; implementing this as a separate table provided with a direct and easy way to access both "kind" of delegates, **without** having to touch a lot of places in the code base.
Adding trainees to the `delegates` list while still maintaining different rights means that we need to go over every single usage of the method, and:
  - make sure it doesn't have to be changed now that trainee in included in it.
  - add an extra trainee/not trainee split when needed.

It's also worth noting that at the time of implementation Trainees were supposed to be a totally optional status in the Delegate promotion process, and met a fairly restricted use case; at this time the plan was to make a quick and straightforward implementation.
Should we have known the plan was to streamline the thing up to a point where it's mandatory and reaches basically every committee, we would have most likely put some more thoughts into restructuring Delegates permissions (ie: do a thorough review of the various `delegates` usage and how we can better accommodate the introduction of this new status).

Definitely feel free to fix this by adding a new entry in the enum, my gut feeling tells me it's going to affect a relatively wide part of the code (I do hope I'm wrong :p).

**Comment by gregorbg** [comment]
Wow, thanks for your thorough feedback! I've taken a shot at this over in #7395. Funnily enough, we were already using a separate entry in the `delegate_status` table. It's really only the "(Trainee) Delegate <=> Competition" associations themselves that were stored separately.
