### ISSUE TITLE
Hide DoB by default in registrations

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#5160]
When registrations are viewed by organizers and/or Delegates the dates of birth are initially visible. Given that there is rarely a use for these to be seen (first timers ID verification is the main reason) and having them visible by default causes more problems than it solves I'd like to suggest the inverse of #3934 : Adding DoB to the list of columns that are hidden by default and have the button to show them at the top of the page.

**Comment by Jambrose777** [comment]
For first time competitors, this information is the third thing I check before approving (the other two being if they’ve paid and their name format) to ensure that the dob isn’t a bogus one. Hiding it by default for all competitors will just encourage more delegates not to check this information and potentially add more bogus dobs to the database.

**Comment by c-goodyear** [comment]
The overlap between Delegates who 1. do not confirm DoBs when first timers check-in and 2. do not look at DoBs before approving registrations is probably high, so I don't think that this would discourage Delegates who are already checking as per 1.

**Comment by EdHollingdale** [comment]
I agree with @c-goodyear - there is no good reason to have them visible most of the time. Since organisers are often accepting registrations and not checking birthdates like Jacob I always check all newcomers in one batch closer to the competition, and then check again at the competition during registration with the competitor.
