### ISSUE TITLE
Old competitions without announced_by

### ISSUE THREAD

**Issue by timreyn** [thewca/worldcubeassociation.org#5188]
On https://www.worldcubeassociation.org/competitions/WC2013 and 24 other competitions which have `announced_at` but not `announced_by`, there's a warning:

> Note: This competition is visible to the public but hasn't been announced yet.

Looks like this error was added in https://github.com/thewca/worldcubeassociation.org/commit/a00a3537349484d36d0b09a8e2a900318882134e#diff-848ffc153c457b964c6c8a9d204cea61

Easy fix would be to change `announced?` to just require `announced_at`, but that would break an assumption here: https://github.com/thewca/worldcubeassociation.org/commit/a00a3537349484d36d0b09a8e2a900318882134e#diff-94edf8bc77a69940d1816d5bc8485d96

@jonatanklosko thoughts on the right way to fix?

**Comment by jonatanklosko** [comment]
So I see two options here:

1. change `announced?` to check `announced_at` only, just as you suggested, and then conditionally render the announcer name depending if it's set
2. set `announced_by` to someone, even if it's not accurate (someone from the WRT as it would look weird for a WST member to have announced a competition)

Both solutions seem straightforward, but ideally `announced_at` and `announced_by` should be either set or not (as otherwise I can see it being a source of some bug in the future), so I'd prefer solution `2.` if it's not too much of a problem. @Jambrose777, @viroulep thoughts?

**Comment by viroulep** [comment]
The Board has a [user](https://www.worldcubeassociation.org/users/125297/edit) we used for regions without Senior Delegates, I think the easiest solution is just to fill the empty announced_by field with that user's id!

Thanks for the report @timreyn!

**Comment by jonatanklosko** [comment]
Oh that's neat, sounds good to me! @Jambrose777 is WRT ok with that?

**Comment by SAuroux** [comment]
I am not @Jambrose777 but I think this is a reasonable solution. :)

**Comment by jonatanklosko** [comment]
I've just run the following on staging and then on production (after doing a backup):
```sql
UPDATE Competitions
SET announced_by = 125297
WHERE announced_by IS NULL AND announced_at IS NOT NULL;
```
Worked as expected, so I believe we can close this!

**Comment by Jambrose777** [comment]
LGTM! Thanks!
