### ISSUE TITLE
Cannot turn on/off registration email notifications for competitions within 28 days

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#5248]
When trying to click "update competition" to adjust this email notification setting, an error pops up to indicate that the date of the competition can't be within 28 days. It seems that this is intended for unannounced competitions to prevent dates that are too soon, but makes it impossible to turn off this setting once the competition is too close in time.

I was recently added to a competition as a delegate within 28 days of the competition, and now have no way to turn off these emails.

**Comment by EdHollingdale** [comment]
This is also discussed in #4673 

While we're at it, can we also change the default value to **not** receive these emails. I am sick and tired of having to disable emails for every competition I delegate or where Speedcubing Australia is a listed organiser, or forgetting to and getting spammed with rego emails. I don't know anyone who actually wants to receive hundreds of registration emails.

**Comment by viroulep** [comment]
Closing to continue the discussion over the "original" issue but I agree something has to be done.

> I don't know anyone who actually wants to receive hundreds of registration emails.

Actually you do, @zeecho mentioned he wants that in the other issue!
I also like to receive all registrations emails, my main motivations are:
  - to know exactly when I have to handle something about registrations (instead of remembering periodically to check the registrations list)
  - to directly have the comment sent with the registration, and being able to conveniently start an email thread with the competitor about it if needed.
