### ISSUE TITLE
Mass refund ability

### ISSUE THREAD

**Issue by UnderwaterCuber** [thewca/worldcubeassociation.org#5258]
As coronavirus spreads a lot of competitions are being canceled and having to refund competitors one by one is pretty messy. I think that the ability to mass refund could be beneficial for situations like this

I think that in order to avoid accidental refunds of the entire competition the system needs to be pretty tight. I'm thinking that all listed delegates for the competition and organizers must confirm that they want a mass refund and that a member of WFC (I believe this would fall under them) would also need to confirm it.

I would love to hear other alternatives or ideas for this :)

**Comment by EdHollingdale** [comment]
I am very strongly against having a button that can do mass refunds on the website. I've gone through long waiting lists and refunded one at a time and it is frustrating, but such control is necessary.  

I don't see how writing an email to the WFC and waiting for them to get back to you is a more convenient thing than just issuing them yourself one at a time. Additionally, the finances of competitons are the responsibility of organisers and not the WFC - it is not really our scope. I have previously pushed to limit the control that anyone with admin rights on the website has over my organisation's stripe account.

**Comment by viroulep** [comment]
The situation is really exceptional and by the time we implement this it would - hopefully - be over.
It's very tedious to deal with this but I don't think it would be a good idea to add a general feature for this anyway.
You may also have competitors who ask you to keep their registration fee as a donation :)

I'm going to close this for now because I don't think we're going to implement the feature as it's suggested, but feel free to re-open if you have alternative ideas!
