### ISSUE TITLE
Homepage improvement

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#53]
Perhaps show a list of upcoming competitions, or competitions near you?

**Comment by jbcm627** [comment]
Ideas from Oliver:

Sorry if this question has been raised before, but since we have a new website, would it make sense to somehow show the different announcements in different colors too?

Right now the sticky is blue and all the rest is natural. It could be something like:
- sticky remains blue on the top
- announcing a new competition could be green
- posting a result could be red
- posting other announcements (like new regulations, new TNoodle, etc.) could be dark grey or black

I don't mind other colors than suggested, just have them seperated, so it's obvious which one is which.

Also, we could use a different, darker color for posted results for a competition here too: https://www.worldcubeassociation.org/results/competitions.php

This way, people would not click on the competition, if they see that the results are still missing. Also, we could check faster too which ones are yet to be submitted.

**Comment by pedrosino** [comment]
I guess having separate lists with the different announcements would be cool.
Maybe have them collapsible or something, and with the colors.

**Comment by jbcm627** [comment]
I like @pedrosino's idea.

As with the competitions page, I don't think a re-design of the homepage needs to reflect the current homepage at all. The current layout/functionality I (personally) do not find useful. Taking a look at google analytics could show what things people most commonly access, and so may suggest what sort of features would be best for the homepage.

**Comment by viroulep** [comment]
This was actually addressed by #5669.
