### ISSUE TITLE
Old post in latest news section

### ISSUE THREAD

**Issue by AlexKatyukov** [thewca/worldcubeassociation.org#5929]
**Describe the bug**
The old post about dues system is shown into latest news section at the moment.

**To Reproduce**
1. Go to homepage
2. See error

**Expected behavior**
Not sure what should be here, but I think that the post from 2018 is pretty old.

**Screenshots**
![image](https://user-images.githubusercontent.com/18090165/101465959-a3e8a880-3951-11eb-9e6a-1e1386a11e71.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 Home Edition
 - Browser Yandex (it's a Chromium) 
 - Version 20.11.2.78 (64-bit)

**Comment by viroulep** [comment]
The relevant line for selecting the latest post: https://github.com/thewca/worldcubeassociation.org/blob/master/WcaOnRails/app/controllers/posts_controller.rb#L39

It orders by sticky first, then created date (latest first).
Because the date is so far in the past, the post must still be sticky (which seems to be the case as going [here](https://www.worldcubeassociation.org/posts/introduction-of-wca-dues-system) shows a blue header).

@EvilAngel00 do you mind taking a look at this?
It should simply be a matter of un-sticking the dues post.

**Comment by EvilAngel00** [comment]
Done! 

For some reason that post was stickied until 2020-12-22.

**Comment by viroulep** [comment]
Thanks!
