### ISSUE TITLE
Permalink for db export

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#60]
The zip should contain the version number and date, but the URL should stay constant.

**Comment by lgarron** [comment]
I do this at alg.cubing.net
<alg.cubing.nethttps://github.com/cubing/alg.cubing.net/blob/d180ab9281d4ac9dbc73f6e8b3c124db1b380976/Makefile#L36>
using
a simple 302 (temporary) redirect:

$ curl -I https://alg.cubing.net/source/alg.cubing.net.zip
...
Location: https://alg.cubing.net/source/alg.cubing.net-2015-05-06.zip

Unfortunately, it seems Chrome now saves the file as alg.cubing.net.zip
instead of alg.cubing.net-2015-05-06.zip :-(

»Lucas

**Comment by lgarron** [comment]
I implemented this at alg.cubing.net [using a simple 302 redirect](https://github.com/cubing/alg.cubing.net/blob/d180ab9281d4ac9dbc73f6e8b3c124db1b380976/Makefile#L36):

    $ curl -I https://alg.cubing.net/source/alg.cubing.net.zip
    ...
    Location: https://alg.cubing.net/source/alg.cubing.net-2015-05-06.zip

Unfortunately, it seems Chrome now saves the file as `alg.cubing.net.zip`
instead of `alg.cubing.net-2015-05-06.zip`. :-(

**Comment by FatBoyXPC** [comment]
This can be done setting the headers up appropriately and outputting the file contents to the browser. I'm not sure how to do it in Ruby (or RoR for that matter, either), but it should be trivial to do so. Here is how to do it in PHP: http://stackoverflow.com/questions/12295604/php-simple-download-script

This would make it very easy to have something like worldcubeassociation.org/database-export.zip or something, and the filename would be correct.

**Comment by jfly** [comment]
I mentioned this somewhere, but I cannot remember where. With our new database export, we could require that people be logged in to access it. This would let us keep track of who's actually using the export.
