### ISSUE TITLE
Calendar feed

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#64]
This sounds fun and easy =).

**Comment by StachuDotNet** [comment]
I did a bit of googling on this, and found that the only popular service to have done this before was Google. They have since stopped offering this service.

Is this still a thing? If so, can you link the (xml?) format or is there no current standard and you're just hoping that we can have an API for this sort of thing?

**Comment by jfly** [comment]
Oh really? That's a bummer. When I created this issue (almost a year ago, wow!), I probably assumed that there was some standard (a la rss) that we could just implement. It sounds like that's not the case? What about [iCalendar](https://en.wikipedia.org/wiki/ICalendar)?

What's the service that Google has stopped offering?

@lgarron might be able to provide some input here.

**Comment by StachuDotNet** [comment]
I googled hard for a while trying to find a common format (like in normal RSS feeds), but couldn't find anything.

*shrug*

**Comment by lgarron** [comment]
`.ics` is ridiculously easy: https://github.com/lgarron/wca_ical/blob/master/wca_competition_feed.php#L181

**Comment by gregorbg** [comment]
We do have iCal exports for competitons now.

**Comment by lgarron** [comment]
> We do have iCal exports for competitons now.

Out of curiosity, where is is this? I can't find a link at e.g. https://www.worldcubeassociation.org/competitions?utf8=%E2%9C%93&region=USA&search=&state=present&year=all+years&from_date=&to_date=&delegate=&display=list
