### ISSUE TITLE
Cannot issue refund for single registrant

### ISSUE THREAD

**Issue by khkellis** [thewca/worldcubeassociation.org#6420]
**Describe the bug**
When clicking "Refund Payment" on a competitor's registration page, the error page with "We're sorry, but something went wrong. If you are the application owner check the logs for more information." appears.

When navigating back to the page, the "Payment History" does not show a refund. 

**To Reproduce**
https://user-images.githubusercontent.com/27914581/129586527-c6992021-15cf-46d4-96b6-eeff1887c394.mp4

**Expected behavior**
Competitor gets refunded. 

**Screenshots**
See attached video. 

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version: Accessed 8/16/2021

**Additional context**

**Comment by gregorbg** [comment]
For reference, the details of this issue have been communicated via email due to the confidential personal details involved in the payment process.

In general, this was an error on Stripe's side, we only need to worry about showing better error messages instead of the generic "Something went wrong".
