### ISSUE TITLE
Registration table appearance bug

### ISSUE THREAD

**Issue by Jambrose777** [thewca/worldcubeassociation.org#6789]
**Describe the bug**
When on the registration page, after accepting a registration the page can look like this:
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/11577241/161171667-c8cb11ba-8a07-499c-b28c-a0fdbb4b1145.png">

**To Reproduce**
1. Go to a competition's registration page
2. click show events
3. accept a registration from the waiting list to the accepted list
4. notice the table messing up.

**Expected behavior**

**Additional context**
This is due to the footer updating to no longer include the event data. so the total price accumulated shows up in the column for an event, causing the big space.

**Comment by kr-matthews** [comment]
For the record, I took a look into this to try and fix it but couldn't figure it out. `do_actions_for_selected.js.erb` seems to be (re)rendering the table footer (right at the end of the file), but it doesn't seem to bring along the instance variables `@show_events` etc which it needs in order to know which footer columns to show/hide. I tried messing around with these instance variables in various ways, but since everything in Ruby is passed around implicitly I was pretty lost, and nothing worked.

I'd be happy to try again if someone can explain what's going on, or maybe this note will help whoever next tries to resolve this.

**Comment by gregorbg** [comment]
The variables are being defined in the controller `registrations_controller` right at the top of the `do_actions_for_selected` method. These `@show_*` variables rely on the `?show_*=...` query param part of the URL.

But actually, the HTTP `PATCH` form that gets built in `edit_registrations.html.erb` does not include these query parameters!  So to be precise, the re-rendering of the table footer _does_ bring along the `@show_*` variables, but they are all being set to false. Hover over the "Accept registration" button, right-click and Inspect in your browser dev tools. Navigate a few nodes up in the DOM tree to find the Form that is created on the fly for the "button bar" and see for yourself to better understand what's going on here :)

**Comment by gregorbg** [comment]
You will probably have to change the URL at `edit_registrations.html.erb:35`. The `*_path(@model)` helpers can generate additional query params as per https://api.rubyonrails.org/classes/ActionView/Helpers/UrlHelper.html#method-i-link_to
