### ISSUE TITLE
Paying for the website

### ISSUE THREAD

**Issue by jfly** [thewca/worldcubeassociation.org#68]
See the WST's costs [here](https://github.com/thewca/worldcubeassociation.org/wiki/Costs)

Some ideas for paying for the website:
- Ads. See discussion with the board: https://groups.google.com/forum/#!topic/wca-website/LWlIh9218P8.
  - Fun, meaningless thing to look at: http://www.worthofweb.com/website-value/worldcubeassociation.org/. I (@jfly) talked to a good friend of mine who works in the ad industry, and he says that this number is overestimated.
- Donations (patreon looks cool!)
- Collecting money from competitions. There are a few variants on this:
  - $1 per competitor per competition: we could call it a "results posting fee".
    - Pros: There's no way for delegates to dodge this fee.
    - Cons: This is trivial for developed countries to pay, but might be a measurable burden in some regions of the world.
  - The website now supports payments via stripe. We could take a percentage of every payment done on the WCA website.
    - Pros: This is nice because assuming that competition prices are fair, this will accurately share the load across the world by economic status.
    - Cons: This might incentivize delegates to not use the WCA website for registration, or come up with clever ways of reducing registration fees but charging money in other ways.

**Comment by gagou9** [comment]
As I said already, I'd prefer to give 10€ a month for paying a server than having ads. 
Advertisement = tracking = mass surveillance. Say hello to the NSA :)

**Comment by FatBoyXPC** [comment]
Pretty sure it's safe to say hello to the NSA anyway.

**Comment by pochmann** [comment]
> I'm sure everyone would be happier if we had a beefier server

I wouldn't be happier with a beefier server if it means annoying ads.

**Comment by keemy** [comment]
Not advocating for ads but if enough people decide ads are a good idea I think it would be better to use set up deals with cubing related websites for ads rather than just slapping on adsense. I think  this would avoid much of the issue people seems to have with privacy and would allow for greater control over what can show up on the website.

**Comment by lgarron** [comment]
> set up deals with cubing related websites for ads

Unless we come up with a "neutral" way to do this, this puts us on the position of promoting particular third parties in the puzzle market.
Given the relationship that some national organizations try to maintain with Seven Towns, I don't think this would be a good idea. That, and I think we should try to stay neutral on principle.

I'd rather personally donate $10/month instead (and I effectively have been doing that, since I haven't asked for reimbursements for WCA Dreamhost hosting).

**Comment by keemy** [comment]
I see what you are saying and actually agree that donations and/or competition fees could be a better options. I was just saying if ads then I would suggest direct partnerships. 

> Given the relationship that some national organizations try to maintain with Seven Towns, I don't think this would be a good idea.
Since I was only comparing to just slapping on an ad network this problem would remain either way, whatever non Seven Towns websites could easily buy out the ads through that network and they would show up anyway. As for being "neutral" I assume just letting it go to the highest bidder would be at least fair in some sense.

**Comment by gagou9** [comment]
Heyo!

I'd be ok to have a partnership with a cubing related company/whatever for ads. But of course i'd prefer no ad at all (anyway uBlock rocks and works for Chrome/chromium and Firefox).

I'd still like to do some kind of "donation campaign" for the WCA, and I'm pretty sure this would make us get enough money for some time. And if it doesn't work enough, we could switch to something easier/more profitable.

**Comment by fw42** [comment]
:-1: to ads. I think asking competition organizers to (voluntarily) donate a part of their competition "profit" would work surprisingly well.

**Comment by gagou9** [comment]
> to ads. I think asking competition organizers to (voluntarily) donate
> a part of their competition "profit" would work surprisingly well.

++++ !

**Comment by pingskills** [comment]
I don't know the history here. How are we currently paying for hosting costs?

**Comment by jfly** [comment]
The original post is a lie: we're currently using aws credits that were donated by @keemy. There have been some other minor expenses (tarsnap, DNS, https certificate) that I've paid for out of my own pocket.

We are going to have to figure something else out before we run out of aws credits. I'll reach out to you directly to talk about what those plans are looking like.

**Comment by gagou9** [comment]
I would still be in favor of a call for donations ;)

2016-06-27 9:11 GMT+00:00 Jeremy Fleischman <notifications@github.com>:

**Comment by jfly** [comment]
We now have a financial committee (see https://www.worldcubeassociation.org/posts/start-up-of-the-wca-financial-committee) to worry about this sort of stuff. I'm going to go ahead and close this issue.
