### ISSUE TITLE
Trainee Delegates on Staff Mailing List

### ISSUE THREAD

**Issue by Epride** [thewca/worldcubeassociation.org#6911]
**Describe the bug**
Trainee Delegates currently receive communications sent to the WCA Staff Mailing list

**Expected behavior**
As Trainee Delegates are not staff they should not receive these. They should only be receiving reports

**Comment by gregorbg** [comment]
staff@ is a "meta-list" that we do not directly sync members to. Instead, it forwards to several lists like software@, results@, board@, etc.. that we actually _do_ sync members to.

In this instance, the error occurs because we sync Trainee Delegates to `delegates@worldcubeassociation.org`. Are Trainees supposed to be part of delegates@? If yes, this is a flaw in the way we conceptually designed the staff@ setup and not an actual bug :innocent:

**Comment by gregorbg** [comment]
Kindly ping @Epride

**Comment by Nevseros** [comment]
Following up this issue; has the discussion gone any further?

**Comment by dunkOnIT** [comment]
Should `delegates@wca` perhaps be split into `delegates@wca` for all Junior and above, and `trainees@wca` for trainees only? Then delegate reports can be sent to both groups, and _only_ `delegates@wca` is part of `staff@wca`.

To my mind that seems like a pretty simple way of implementing this - but my Google Admin knowledge is limited.

**Comment by Epride** [comment]
Apologies for my silence here but the suggestion by @dunkOnIT seems like a fairly reasonable way forward

**Comment by gregorbg** [comment]
Techincal note to people who wish to implement this: You need to touch `WcaOnRails/app/jobs/sync_mailing_lists_job.rb` where currently it syncs `User.delegates` to the `delegates@` list. Create an additional `staff_delegates` scope that includes only Delegates (DB column `delegate_status NOT NULL`) that are not `trainee_delegate` in the DB (how to do this is left as an exercise).

Then add a second line to the sync job referring to `trainees@wca` to sync the existing `User.trainee_delegates` scope to. I have created an empty mailing list that can automatically be found and used by our Ruby code without any additional setup.

**Comment by gregorbg** [comment]
Fixed in #7395
