### ISSUE TITLE
Users can view existence of unannounced competitions through contact form URL. 

### ISSUE THREAD

**Issue by weatherman223** [thewca/worldcubeassociation.org#7034]
While testing links earlier, I found a unique bug that is replicable through other unannounced competitions. 

When using the [WCA Contact form](https://www.worldcubeassociation.org/contact/website), you are able to see that sites exist for unannounced competitions by manipulating the competition ID in the URL. 

This can be demonstrated and replicated with any unannounced competition, even in incognito. The following screenshot was taken before this unannounced competition was confirmed. 

![image](https://user-images.githubusercontent.com/36021082/177389510-86895817-ed6f-4b66-8ade-694579535ee2.png)

This is concerning because locations for larger competitions could be leaked if being kept secret, or other unannounced/rumored competitions in general if someone used the right ID.

**Comment by dunkOnIT** [comment]
Thanks very much for reporting this @weatherman223 ! 

I've been able to replicate it on my end, but just to confirm, it seems like one needs to know the Competition ID in order to execute this? Do you also have a way to find the competitionID of unannounced competitions, or would you rely on educated guesswork for that part?

**Comment by gregorbg** [comment]
Educated guesswork is bad enough. For big, international competitions you can scrap the "educated" part because it's literally always `WC20XX`. Especially for CubingUSA, who want to keep their Nationals location a secret, this is bad.
