### ISSUE TITLE
Allow Organizers and Delegates to register for competitions before they open

### ISSUE THREAD

**Issue by simonkellly** [thewca/worldcubeassociation.org#7073]
**Is your feature request related to a problem? Please describe.**
Usually when organizing competitions, we have had to change the registration date to the current time before the competition is announced to allow for the organizers and delegates to register for the competition and avoid having to register themselves when the normal competition registration period opens. I can also envision this being especially annoying if the competition has already been announced and another organizer/delegate is to be added

**Describe the solution you'd like**
Remove the checks to stop someone registering early if they are an organizer / delegate

**Describe alternatives you've considered**
Keep using the current solution of changing the registration date.

**Comment by gregorbg** [comment]
This is not teriibly hard to do in terms of code, but there's a long and heated discussion about the "moral" aspect of this issue. As such, we won't immediately implement it nor accept any PRs.

Right now, the WCA needs to define what is and isn't okay for this procedure. Then we can potentially follow up with the code.

**Comment by EdHollingdale** [comment]
Currently many people already do this.  Before the competition is announced adjust the registration open date to be some date in the past, sign up (leaving registrations for organisers and delegates pending on the waiting list), then adjusting the registration opening to be some date in the future before the competition is announced. Once registration does open the organisers and delegates are the first to be processed since they registered earliest. This is explicitly allowed by 6.2.1.2 of the competition requirements policy.

**Comment by simonkellly** [comment]
The request was mainly for before it is announced, and potentially once announced but registration is yet to open

**Comment by SAuroux** [comment]
@gregorbg As Ed already mentioned briefly, the moral behind this is already solved as this is regulated in WCA's [Competition Requirements Policy](https://www.worldcubeassociation.org/documents/policies/external/Competition%20Requirements.pdf).

So in fact this would be a very helpful Software change to eliminate the annoying back and forth changing of the registration start just to allow Organizers and Delegates to register.

**Comment by simonkellly** [comment]
If this is something that is okay to be implemented, I would be happy to write the PR.

**Comment by dunkOnIT** [comment]
I would advocate for only implementing this so that 6.2.1.2 is provided for in the code, but at this stage not add the functionality for  delegate/organiser to be added _after_ a competition opens with any priority, as that seems like a more complex issue - both in terms of the principle and the ease of it. 

@gregorbg would you have any opposition to that? Limiting the scope in that way would seem above board, and I'd be eager given that we have a willing contributor.

**Comment by Jambrose777** [comment]
Im not following why having organizer/Delegates being able to register after a competition is announced but before registration opens is an issue. The Ethics committee has already ruled that it would be **unfair and unreasonable** for a Delegate / Organizer to put in so much work putting on a competition and not be able to compete because they couldn't pre-register.

**Comment by gregorbg** [comment]
Gotcha, thank you everybody for the direct and clear feedback that apparently I was wrong and there already is a consensus 😄
Will remove the "Controversial" label and consider this for the next round of project planning.

**Comment by dunkOnIT** [comment]
@simonkellly is this still something you would be willing to write the PR for? Looks like we have the green light on implementation!
