### ISSUE TITLE
More fields for delegate reports

### ISSUE THREAD

**Issue by pedrosino** [thewca/worldcubeassociation.org#708]
- [ ] "I really like the layout, but maybe some window like ‚Course of the competition‘ or ‚Competitionflow‘ would be good? Right now you only can write this in the last window under Remarks, but in most of the competition reports it’s directly under the organizational stuff." -Linus
- [ ] "Also I noticed that there is not really an appropriate window for stuff like ‚registered persons‘ compared to competitors who actually came to the competition, this may be at a good place right under the 'Competitors‘, if even necessary :-)" -Linus

**Comment by LinusFresz** [comment]
I have one additional thing (maybe some kind of 'bug'):
At least at one competition there is the link to the discussion-thread in the googlegroup missing: [Cube4Cam Report](https://www.worldcubeassociation.org/competitions/Cube4Cam2016/report)

I am not sure if this is a bug or done manually right now, because for the other two submitted reports from today there is a link to the thread (like at the [Fuzhou Open 2016 Report](https://www.worldcubeassociation.org/competitions/FuzhouOpen2016/report)).

**Comment by pedrosino** [comment]
It is done manually now.

**Comment by dunkOnIT** [comment]
Closed in favour of #483
