### ISSUE TITLE
Order Scrambles on Competition Page by isExtra and scrambleNum rather than scrambleId

### ISSUE THREAD

**Issue by sam596** [thewca/worldcubeassociation.org#7273]
See the following scramble pages:

https://www.worldcubeassociation.org/competitions/AustralianNationalsFMC2022/scrambles?event=333fm
https://www.worldcubeassociation.org/competitions/AsianChampionship2016/scrambles?event=333mbf
https://www.worldcubeassociation.org/competitions/CaltechSpring2014/scrambles?event=222 (the weirdest one :P)
https://www.worldcubeassociation.org/competitions/CubanOpen2016/scrambles?event=333
https://www.worldcubeassociation.org/competitions/GernikaOpen2015/scrambles?event=333mbf
https://www.worldcubeassociation.org/competitions/MedanOpen2015/scrambles?event=333mbf
https://www.worldcubeassociation.org/competitions/VenezuelaNationals2015/scrambles?event=333mbf

These oddities, sometimes major (like CaltechSpring2014), sometimes minor (like MedanOpen2015), I believe are caused by the scrambles being presented in order of their unique auto-incremented `scrambleId`, but when scrambles have to be retroactively altered by WRT, we change the scrambleNum and/or isExtra and don't touch the unique ID field.

This should be fixed by presenting the scrambles in order of their scrambleNum, with Extras at the bottom, meaning they should have `ORDER BY isExtra, scrambleNum`.

**Comment by viroulep** [comment]
Thanks for the investigation and making sure this was the issue!
When reading this it was fairly obvious we didn't have any default order, and there is actually a very easy way to make sure there is a decent default order so I submitted a patch in #7274.

I also included the `groupId` in the default order since I noticed when testing the changes that it also has to be taken into account to display the scrambles correctly.
