### ISSUE TITLE
Error running db:migrate on a fresh docker container of the WST website

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7403]
## Steps to reproduce:

1. Follow setup guide defined in the [README](https://github.com/thewca/worldcubeassociation.org/blob/master/README.md) // Open repo in Github Codespace
2. Run `docker compose up`, wait for the container to be ready for connections
3. Attempt to connect to localhost endpoint
4. Greeted with a screen requesting that `bin/rails db:migrate RAILS_ENV=development` be run
5. `cd` to `WcaOnRails` in a `docker exec` terminal, run the command from (4)
6. You may encounter a compatbility issue here. Adding 7.0 to the end of the file's class declaration seems to help, ie: `class RenameDrupalIndicesToBeUnique < ActiveRecord::Migration[7.0]`
7. Repeat Step 5 if error in (6) encountered
8. Encounter error: `Mysql2::Error: Table 'wca_development.cache' doesn't exist`

I've followed a variant of this process and ended up at Step 8 on 2 different machines and in a codespace. Looking for anyone who has successfully set up the WCA website recently who can report on whether they encountered this issue, or anyone follow the README steps in a fresh docker container without issue.

**Comment by dunkOnIT** [comment]
@cranemit looks like you recently set up the WCA website locally for the first time - did you run into any of this?

**Comment by simonkellly** [comment]
When I initially set up the website in July I ran into these errors. I added the [7.0] thing at the end of the class declaration, but in the end I just removed all code within all the migrations, then ran them all, and then everything has worked fine since.

**Comment by cranemit** [comment]
I first set it up around a month ago and I was seeing the `RenameDrupalIndicesToBeUnique` errors. I tried a few things unsuccessfully, but I'm not sure what I ran, and ended up going with the `Run directly with Ruby` option instead to get the site running.

**Comment by navaneethkp36** [comment]
@dunkOnIT I ran the application directly with ruby. Did not use docker. I just faced the compatibility issue that you mentioned above while running migrations. Adding 7.0 at the end of class declaration solved it.

**Comment by gregorbg** [comment]
A bit of insight into the migration thing: Historically, migrations did not need the `[X.Y]` versioning suffix. Ruby proposes adding it because we currently use Rails `7.0`, but older migrations were created at a time when `< ActiveRecord::Migration` was enough.

That being said, **under normal circumstances you should not have to run all historical migrations in our repo anyways**. The reason why Rails prompts you to please run migrations is that the population of DB (dummy) data does not work correctly. Normally, we populate the DB in a way that has all schema changes already applied. So the case in point of this issue is not how to fix migrations, but rather how to fix the seeding process so that running migrations doesn't even become an issue. I have attempted to fix this in #7448
