### ISSUE TITLE
Competition edit form getting messed up after delegate resignation

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#7523]
If a competition has a delegate/trainee delegate, and if the delegate has resigned, the competition edit form is no longer showing the delegate, but the database still have the ex-delegate as a delegate. Because of this, `delegates_must_be_delegates` validation is failing.

**Comment by viroulep** [comment]
This affects only *upcoming* competitions; I'd suggest anyone looking at this to implement a validation on `User`: it would be nice to prevent the change in delegate status (ie: removal) if the user is still assigned to an upcoming competition.
This way the Senior would know they have to make sure any upcoming competition handled by the future former Delegate has to be updated.

**Comment by DanielEgdal** [comment]
I think this also applies to old competitions (WST and WCAT have the thread "Incorrect map data from old (2012/2013) competitions in Ontario"). One of the affected competitions is https://www.worldcubeassociation.org/competitions/WaterlooFall2012
On that thread I wrote 
"I cannot change the competitions because the only the listed delegate is a former delegate. This was probably broken back in December by this https://github.com/thewca/worldcubeassociation.org/pull/7395. With 63 changed files, I don't quite dare to venture into this part of the code base."
