### ISSUE TITLE
Banned Competitors cannot register to competitions that occur after their ban expires

### ISSUE THREAD

**Issue by Samuel-Baird** [thewca/worldcubeassociation.org#7591]
It was recently brought to the WDC's attention that banned competitors are unable to register for any competitions while they are banned, even competitions past the expiration date of their ban. With many competitions having registration open and filling months before actual competitions, some competitors are at risk of a "prolonged" ban as they may be unable to compete for several months even after their ban has expired. 

We would like this resolved by restricting banned competitors from registering for competitions scheduled to take place during their ban period while leaving the banned competitors free to register for any competitions outside of their ban period.

**Comment by FinnIckler** [comment]
This happens because On registration it is just checked if the user is banned here https://github.com/thewca/worldcubeassociation.org/blob/6f8cdc02c93c5f7c52b386964681587a9f00c5b9/WcaOnRails/app/models/user.rb#L924

Banning a user is implemented via a hidden team for which there is an end date set. 

So to implement this the cannot_register_for_competition_reasons method needs to get a competition as a parameter, which start date can then be checked against the end_date of the membership of the banned team
