### ISSUE TITLE
Improve error logging

### ISSUE THREAD

**Issue by dunkOnIT** [thewca/worldcubeassociation.org#7658]
There are two sides to this:
* Client-side error messages
* Server-side error logs

On the client-side, current users receive a generic error message when something goes wrong. This is good for security (as it makes it harder for malicious actors to know what code they're causing to execute), but obviously poor for our ability to investigate errors reported to us. 

On the server-side, our logs are massive (34m lines in 24 hours) and unwieldy.

A few proposals here: 
- Client-side: consider implementing general error classes that can be displayed to the user, for initial investigation purposes
- Server-side: Give each error a unique code, for ease of grouping/analysis
- Server-side: Consider logging errors to a dedicated file, either instead of or in addition to the main logfile we use

**Comment by FinnIckler** [comment]
And we could include the `:request_id` in the error page so we could cross reference someone reporting an error in the logs.

**Comment by FinnIckler** [comment]
Here are some stats that should else us choose a log level. From 33,749,919 total logs in the last 24 hours we have:
- 5,154,649 info logs
- 183 Warn logs
- 12 Error logs (we get emails about these if they concern jobs)
- 12,905 fatal logs (this is much more then usual because of a missing migration and the disk being full just now)
So switching to Info would save us about 28 million logs per day

**Comment by FinnIckler** [comment]
Honestly I think even `Warn` would be enough for us to catch everything as all the performance metrics we are getting with `info` is also in new relic
