### ISSUE TITLE
Nearby Competitions shows too many

### ISSUE THREAD

**Issue by coder13** [thewca/worldcubeassociation.org#7712]
**Describe the bug**
Nearby Competitions (Within 5 days and 10km) doesn't do what it says

Should this only show competitions within 5 days and 10km?

**Expected behavior**
To see the competitions that match the description

**Screenshots**
![image](https://user-images.githubusercontent.com/881394/222253669-d14f3c83-ae8a-446b-a50f-2184700d2010.png)

**Comment by FinnIckler** [comment]
mh.. we just deployed a fix that affected this bit in the codebase, maybe it changed something in the sorting by accident?

**Comment by simonkellly** [comment]
Im not 100% sure about this, but I think it displays some in yellow which are close, but not illegal, and ones in red which would violate the rule.

**Comment by gregorbg** [comment]
Closing as this is a non-issue. @simonkellly Feel free to take this as inspiration for your refactor to introduce some labels or otherwise separate the tables. (I think the status quo when you started the refactor was actually that the tables _are_ separated, they only recently got married in https://github.com/thewca/worldcubeassociation.org/pull/7534)
