### ISSUE TITLE
Disable force comments validation for non-competing registrations

### ISSUE THREAD

**Issue by jonatanklosko** [thewca/worldcubeassociation.org#7775]
Some competitions have organizers/delegates that don't compete (have no registration), however on WCIF patch we try to create one with `is_competing = false`:

https://github.com/thewca/worldcubeassociation.org/blob/0518f057433bd0c5bc318f4516e20ea5d583759e/WcaOnRails/app/models/competition.rb#L1765-L1771

This breaks on this validation:

https://github.com/thewca/worldcubeassociation.org/blob/0518f057433bd0c5bc318f4516e20ea5d583759e/WcaOnRails/app/models/registration.rb#L278-L283

It would make sense to disable that validation for non-competing registrations, which we already do here:

https://github.com/thewca/worldcubeassociation.org/blob/0518f057433bd0c5bc318f4516e20ea5d583759e/WcaOnRails/app/models/registration.rb#L251-L256

---

On a more general note: whenever there is an organizer/delegate that doesn’t compete, we create a registration for them the first time there is a WCIF patch; which shouldn’t necessarily break anything (other than this issue), but it is a bit weird.

**Comment by gregorbg** [comment]
> Sorry for introducing this edge case -- let me know if you think it's worth rethinking the design of non-competing registration.

I think the design is alright, we were just not very thorough at review about validations that do or don't make sense with the new `is_competing` flag.

We've recently run into several issues mostly because of organisers who are filled in on the "Organisers" field of the competition form, that are then synced back in tools like WCA Live and receive a registration via WCIF PATCH when syncing there.

Design-wise it makes complete sense to give these people a non-competing registration if you understand registration as "takes part in the competition". It simply depends on what "taking part" means and this includes rethinking terminology and concepts. This is always a part of introducing new designs :)
