### ISSUE TITLE
Show error if Delegate uploads results with an event without competitors

### ISSUE THREAD

**Issue by danieljames-dj** [thewca/worldcubeassociation.org#8050]
Currently, if there is an event without any participants, the Delegate has to remove the event from the 'manage events' page. But if the Delegate removes just the rounds and not the event, it will show a warning. Instead of the warning, it should be error and the error should ask the Delegate to remove the event in case there are no competitors.

**Comment by EdHollingdale** [comment]
Hi Daniel, this won't quite work, since Delegates can't remove events from announced competitions as they don't have the correct permissions. It is somewhat common this could happen (e.g. there is 5bld at a comp but no one decides to compete in it, poor scheduling meant an event had to be removed). In the past its always been the case that the Delegate should submit the results and then ask WRT to remove the event - to me this means there should be a warning but not an error.

**Comment by danieljames-dj** [comment]
Hi @EdHollingdale you are right, I forgot about the removing event flow from WRT. After I created this issue, Sébastien reminded me about the same. The reason why I created this issue was that in case there are results JSON with no competitors in an event, it will break the WRT result posting flow. But anyway there is a discussion going on in slack to decide how to tackle the issue. Since this Github issue is no longer relevant, I'll close this.
