### ISSUE TITLE
Bug with location searching events on WCA live 

### ISSUE THREAD

**Issue by advay-c** [thewca/worldcubeassociation.org#8182]
**Describe the bug**
When I try to see future competitions near my area on WCA live the website shows me the current statistics on a competition currently going on far away from my location. 

**To Reproduce**
1. Go to WCA live website 
2. Click find nearest competition
3. Accept location
4. Sends you to a competition currently going on

**Expected behavior**
I expected to be shown a list of some sort showing future competitions near my location.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 116.0.5845.97

**Comment by dunkOnIT** [comment]
Hi Advay - WCA Live is not intended for discovering competitions near you. As such, I am closing this issue as not planned. 

However, you do raise a good point in terms of user experience of finding competitions relevant to you. I have created [an issue](https://github.com/thewca/wca-live/issues/181) in the WCA Live repo with this idea.

**Comment by jonatanklosko** [comment]
This behaviour is expected, the location icon only shows up if there are ongoing competitions and it directly navigates to closest of them. This icon primarily meant to be a shortcut for people at the competition or in the same country, so they don't have to scroll through the list.

For searching competitions in general the WCA website should be preferred, because competitions are visible on WCA Live only once imported, and some organizers do that shortly before the competition date.
