### ISSUE TITLE
Clarify how the website should build the Regulations

### ISSUE THREAD

**Issue by viroulep** [thewca/worldcubeassociation.org#867]
See comments in #747 [here](https://github.com/cubing/worldcubeassociation.org/pull/747#discussion_r77770550).

Right now the website is still aware about `regulations-data`, and that it has to use the `wrc` compiler on the Regulations and its translations.

It seems that @jfly would basically want to do a `wget app/views/regulations`, meaning we'd have to move `regulations-data` and the build script some place else (the idea is: there is still too much Regulations stuff in the build system, and the website doesn't have to know about the format of the Regulations).
But I'm also not sure it's the job of the WRC to know what format the website expect :p 

@jfly, do you have a workflow suggestion for the @cubing/wrc-team to achieve this?

In the current setup we have four sources of information that we combined to build all the views:
- `regulations-data` which contains the history
- some static views (index for `regulations/scrambles`, `regulations/history`, `regulations/translations`)  (see [here](https://github.com/cubing/worldcubeassociation.org/tree/master/WcaOnRails/app/views/regulations))
- `wca-regulations`
- `wca-regulations-translations`

The first three sources change whenever the Regulations have a new release (or when TNoodle has a new release). The translations are updated whenever a maintainer wants to publish an update, we don't have a release system for this.

**Comment by jfly** [comment]
I really like the idea of the `wrc` (compiler). I think it should provide everything we (the wca website) need in order to build the regulations (as mentioned [here](https://github.com/cubing/worldcubeassociation.org/pull/747#discussion_r77770550), right now there is a lot of bash logic required for us to run `wrc` correctly).

Maybe the problem here is that we don't agree on what it means to "build the regulations". I consider everything that lives under the `/regulations/` url to be owned by the WRC and therefore anything required to get those pages to work is "building the regulations".

By the argument above, it would probably make sense for us to move this directory https://github.com/cubing/worldcubeassociation.org/tree/master/WcaOnRails/app/views/regulations out of the worldcubeassociation.org repo and into a repo maintained by the WRC. I realize there's some ruby stuff in there, but I'd say that we have an agreed upon contract that if the WRC wants an HTML file to show up with the WCA navbar, then they have to name the file `*.html.erb`, and they have to put `<% provide(:title, 'TITLE HERE') %>` at the start of the file.

**Comment by jfly** [comment]
I'm happy with how this is now. @viroulep, feel free to reopen if you disagree.
