### ISSUE TITLE
Unable to add Championship Type to Competition

### ISSUE THREAD

**Issue by Epride** [thewca/worldcubeassociation.org#9097]
**Describe the bug**
Upon adding a championship type to an unannounced competition it not longer becomes possible to save the competition. I have tried in both the organizer and admin view

**To Reproduce**
1. Go to https://www.worldcubeassociation.org/competitions/OC2024/edit
2. Click on Add championship type "Oceania"
3. Click on "Save your changes" 

**Expected behavior**
Should be able to save the comp after adding a championship type

**Comment by dunkOnIT** [comment]
## Suspected cause: 

`championship.rb` validates inclusion of the given `championship_type` in the list of CHAMPIONSHIP_TYPEs, which includes the following values:
- `world`
- Each continent name prefixed by `_` (eg, `_Africa`)
- Each iso2 2-letter currency code

The `championship_type` being passed by the frontend for is not consistent with this list - we are passing `Africa`.

## Possible fixes: 
- Have the frontend prefix continent names with `_` (seems the most technically correct to me)
- Change the values in CHAMPIONSHIP_TYPES to not include the `_` prefix (I believe these are values in the db though, so not trivial)
- Prepend any continent names with `_` in the competition model (GROSS)

## Initial investigation: 

Backend is returning a 422 with this stacktrace:

```bash
NoMethodError (undefined method `errors' for an instance of Array):
rails        |   
rails        | app/models/competition.rb:2426:in `rescue in block in set_form_data'
rails        | app/models/competition.rb:2423:in `block in set_form_data'
rails        | app/models/competition.rb:2404:in `set_form_data'
rails        | app/controllers/competitions_controller.rb:676:in `update'
rails        | lib/middlewares/warden_user_logger.rb:13:in `call'
rails        | lib/middlewares/fix_accept_header.rb:14:in `call'
```

It appears to be related to this code (`models/competition.rb`): 
```ruby
if (form_championships = form_data["championships"]).present?
  self.championships = form_championships.map do |type|
    Championship.new(championship_type: type)
   end
 end
```

Assigning the array of Championship objects to `competition.championships` _seems_ to be where the wheels are falling off here. My first suspicion is a validation failure of some kind, but I can't see any 2

Tagging @gregorbg in case the issue here is obvious to you.

**Comment by GuidoDipietro** [comment]
For the record, a related issue is happening to us for the South American Championship 2024.

We will have two competition sites for this event, as one will be the full SAC2024 and the other the FMC only competition, SACFMC2024.

For the first, the website already shows it as a Championship:

![image](https://github.com/thewca/worldcubeassociation.org/assets/48221146/2661d809-664b-4c6a-a360-1b86d443c126)

But the organizer view doesn't:

![image](https://github.com/thewca/worldcubeassociation.org/assets/48221146/448b7b29-e8c2-4f60-9757-47c125cc2400)

With this in mind, it is impossible to set a Continental Championship for South America on the SACFMC2024 site.
The "save changes" button does nothing.

This is blocking for our announcement.

**Comment by GuidoDipietro** [comment]
Just to mention that my issue is still present even when this was closed as completed

**Comment by FinnIckler** [comment]
Yes, because the changes are still being deployed to the main website
