### ISSUE TITLE
Summer Time makes .ics download be out by an hour

### ISSUE THREAD

**Issue by c-goodyear** [thewca/worldcubeassociation.org#9249]
**Describe the bug**
Now central Europe has moved from CET to CEST, when the "Add to calendar" button is clicked and the .ics file is generated, the times are incorrect.

**Expected behavior**
Daylight savings times to be accounted for.

**Screenshots**
Competition page schedule with local timezone:
![image](https://github.com/thewca/worldcubeassociation.org/assets/45567122/e93df11f-4fd2-4864-be37-28ca6b1b3eb3)
Google calendar import with local timezone:
![image](https://github.com/thewca/worldcubeassociation.org/assets/45567122/d30d85ba-6486-4e57-bb01-a4191a5022ef)
Me thinking check-in might be starting before 8 in the morning:
😱 

**Additional context**
This is quite a useful feature, because we use the calendar import as Delegates to easily update actual group time start and finishes, to be able to adjust the schedules on the WCA page at a convenient later time if we end up running very ahead / behind and need to reflect such changes for future references. Having it on a digital calendar with phone access is infinitely better than writing it on some paper with a list of all groups on it (which have a high chance of going missing).

**Comment by gregorbg** [comment]
I have just downloaded the ICS file for this specific competition and the contents look good to me...

The website displays it as 08:30 in my local timezone setting, and based on your screenshot this is what you intended.
The ICS file available [here](https://www.worldcubeassociation.org/competitions/FuresoBeginnings2024.ics) internally lists the event as UTC 06:30, which is the correct UTC timestamp now that CEST is here (because CEST=UTC+2)

![image](https://github.com/thewca/worldcubeassociation.org/assets/6136469/cd605d31-b8af-4741-8a3c-96fc03a73652)


As such, I am inclined to blame your calendar import tool...
