### ISSUE TITLE
Mass Email should use BCC

### ISSUE THREAD

**Issue by KitClement** [thewca/worldcubeassociation.org#930]
Just realized how much I use this feature on CUSA, and how much I'll miss it when it's gone.  Haven't used WCA for a comp yet, but Caleb seemed to indicate that this isn't a feature yet. 

Being able to mass email out to all competitors is super useful for sending out pre-comp instructions, and I use it before every competition.  It would be great to just have a way to get all the emails in a text format like:

`Name <email@host.com>,`

This will allow competition organizers to at least send out email via their own email client easily.  I've been doing this with CubingUSA already, as I prefer to use my own email client when doing this, especially with the email limits the CUSA server had.  This is the CUSA mass email system, with emails blurred out:

![image](https://cloud.githubusercontent.com/assets/6166412/19253620/3c9307f6-8f01-11e6-9903-0fa54eac037f.png)

**Comment by jfly** [comment]
Unfortunately, staging is down right now, but this *is* something we support. We provide a link that lets you mass email all competitors using your own email client. I think this maxes out at ~500 emails though, so competitions like US Nationals might run into issues. We'll deal with that when it happens, though =)

**Comment by MatteoColombo** [comment]
I'm not sure if I should open a new issue or if it's ok to write here.

Btw, I think a change is needed in the current mass email system:  at the moment when you click the email button, all the addresses are copied in the "To" form of the client (at least in gmail, both app and webclient). 
It would be better to if they were copied in the BCC form as it is very easy to forget to move them and this could generate some leaks (of the email addresses). 
I've received some complaints in the past because of this.

**Comment by jfly** [comment]
@MatteoColombo, that's good to know! It should be easy to switch this to use bcc.
